export interface BBCategory {
  name: string;
  slug: string;
  emoji: string;
  color: string;
}

export interface BBProduct {
  name: string;
  description: string;
  price: number;
  originalPrice: number;
  discount: number;
  unit: string;
  quantity: string;
  imageUrl: string;
  inStock: boolean;
  isFeatured: boolean;
  isOrganic: boolean;
  tags: string[];
  rating: number;
  reviewCount: number;
}

export const BB_CATEGORIES: BBCategory[] = [
  { name: "Vegetables", slug: "vegetables", emoji: "🥦", color: "#16a34a" },
  { name: "Fruits", slug: "fruits", emoji: "🍎", color: "#dc2626" },
  { name: "Dairy & Eggs", slug: "dairy-eggs", emoji: "🥛", color: "#2563eb" },
  { name: "Snacks", slug: "snacks", emoji: "🍿", color: "#ea580c" },
  { name: "Beverages", slug: "beverages", emoji: "🥤", color: "#0891b2" },
  { name: "Bakery", slug: "bakery", emoji: "🍞", color: "#b45309" },
  { name: "Meat & Fish", slug: "meat-fish", emoji: "🍗", color: "#be123c" },
  { name: "Grains & Pulses", slug: "grains-pulses", emoji: "🌾", color: "#a16207" },
  { name: "Spices & Masala", slug: "spices-masala", emoji: "🌶️", color: "#dc2626" },
  { name: "Oil & Ghee", slug: "oil-ghee", emoji: "🫒", color: "#65a30d" },
  { name: "Dry Fruits & Nuts", slug: "dry-fruits", emoji: "🥜", color: "#92400e" },
  { name: "Cleaning & Household", slug: "cleaning", emoji: "🧹", color: "#7c3aed" },
  { name: "Personal Care", slug: "personal-care", emoji: "🧴", color: "#ec4899" },
  { name: "Tea & Coffee", slug: "tea-coffee", emoji: "☕", color: "#78350f" },
  { name: "Frozen Foods", slug: "frozen-foods", emoji: "🧊", color: "#0284c7" },
  { name: "Baby Care", slug: "baby-care", emoji: "🍼", color: "#ec4899" },
];

const BB = "https://www.bbassets.com/media/uploads/p/l/";

function p(price: number, origPrice: number): { price: number; originalPrice: number; discount: number } {
  const pr = Math.ceil(price);
  const op = Math.ceil(origPrice);
  return { price: pr, originalPrice: op, discount: Math.round(((op - pr) / op) * 100) };
}

export const BB_PRODUCTS: Record<string, BBProduct[]> = {
  vegetables: [
    { name: "Fresh Tomatoes", description: "Firm, red and juicy — ideal for gravies, salads & chutneys", ...p(29,45), unit: "kg", quantity: "500g", imageUrl: BB + "10000200_21-fresho-tomato-hybrid.jpg", inStock: true, isFeatured: true, isOrganic: false, tags: ["fresh","daily"], rating: 4.5, reviewCount: 3421 },
    { name: "Onion", description: "Medium-size onions — everyday kitchen essential", ...p(32,50), unit: "kg", quantity: "1 kg", imageUrl: BB + "10000148_34-fresho-onion.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["staple"], rating: 4.3, reviewCount: 5678 },
    { name: "Potato", description: "Clean & sorted potatoes for all your cooking needs", ...p(28,40), unit: "kg", quantity: "1 kg", imageUrl: BB + "10000159_29-fresho-potato.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["staple"], rating: 4.4, reviewCount: 4321 },
    { name: "Green Capsicum", description: "Crunchy bell pepper — great in salads & stir-fries", ...p(35,52), unit: "pc", quantity: "2 pcs", imageUrl: BB + "10000069_24-fresho-capsicum-green.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["fresh"], rating: 4.2, reviewCount: 1234 },
    { name: "Cucumber", description: "Farm-fresh crispy cucumber for salads", ...p(22,32), unit: "pc", quantity: "2 pcs", imageUrl: BB + "10000102_20-fresho-cucumber.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["salad","fresh"], rating: 4.3, reviewCount: 2156 },
    { name: "Carrot - Orange", description: "Sweet crunchy carrots, rich in Beta Carotene", ...p(35,50), unit: "kg", quantity: "500g", imageUrl: BB + "10000072_18-fresho-carrot-orange.jpg", inStock: true, isFeatured: true, isOrganic: true, tags: ["organic","healthy"], rating: 4.5, reviewCount: 3456 },
    { name: "Baby Spinach", description: "Tender baby spinach leaves — washed & ready to use", ...p(39,55), unit: "pack", quantity: "200g", imageUrl: BB + "40138448_4-fresho-baby-spinach.jpg", inStock: true, isFeatured: false, isOrganic: true, tags: ["organic","leafy"], rating: 4.4, reviewCount: 1567 },
    { name: "Cauliflower", description: "Fresh white cauliflower — tight florets", ...p(40,58), unit: "pc", quantity: "1 pc", imageUrl: BB + "10000074_21-fresho-cauliflower.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["fresh"], rating: 4.2, reviewCount: 2345 },
    { name: "Broccoli", description: "Imported broccoli — rich in fiber & vitamins", ...p(55,80), unit: "pc", quantity: "500g", imageUrl: BB + "10000063_23-fresho-broccoli.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["imported","superfood"], rating: 4.3, reviewCount: 987 },
    { name: "Green Peas (Shelled)", description: "Ready-to-cook shelled green peas", ...p(48,65), unit: "pack", quantity: "250g", imageUrl: BB + "10000284_16-fresho-green-peas.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["protein","fresh"], rating: 4.4, reviewCount: 1678 },
    { name: "Button Mushrooms", description: "Fresh white button mushrooms", ...p(45,60), unit: "pack", quantity: "200g", imageUrl: BB + "10000273_18-fresho-mushrooms-button.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["protein"], rating: 4.3, reviewCount: 876 },
    { name: "Sweet Corn", description: "Sweet & tender corn on the cob", ...p(30,42), unit: "pc", quantity: "2 pcs", imageUrl: BB + "40004992_16-fresho-sweet-corn.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["sweet"], rating: 4.2, reviewCount: 1234 },
    { name: "French Beans", description: "Tender & stringless french beans", ...p(42,58), unit: "kg", quantity: "250g", imageUrl: BB + "40121003_1-fresho-beans-french-round-direct-institutional.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["fresh"], rating: 4.1, reviewCount: 654 },
    { name: "Beetroot", description: "Deep-red beetroot — great for juices & salads", ...p(25,35), unit: "kg", quantity: "500g", imageUrl: BB + "10000047_23-fresho-beetroot.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["healthy","juice"], rating: 4.3, reviewCount: 987 },
    { name: "Cabbage", description: "Fresh green cabbage — crunchy & versatile", ...p(22,30), unit: "pc", quantity: "1 pc", imageUrl: BB + "40005800_6-fresho-green-cabbage-grated.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["fresh"], rating: 4.1, reviewCount: 1543 },
    { name: "Radish (Mooli)", description: "Fresh white radish — great for parathas & salads", ...p(18,25), unit: "kg", quantity: "500g", imageUrl: BB + "10000166_19-fresho-radish-white.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["fresh","winter"], rating: 4.0, reviewCount: 987 },
    { name: "Lettuce - Iceberg", description: "Crisp iceberg lettuce — perfect for burgers & wraps", ...p(49,65), unit: "pc", quantity: "1 head", imageUrl: BB + "40211681_4-fresho-lettuce-iceberg-green-hydroponically-grown.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["salad","imported"], rating: 4.2, reviewCount: 765 },
    { name: "Ginger", description: "Fresh aromatic ginger root — essential for tea & cooking", ...p(25,35), unit: "kg", quantity: "100g", imageUrl: BB + "10000117_22-fresho-ginger.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["spice","essential"], rating: 4.4, reviewCount: 3210 },
    { name: "Garlic", description: "Farm-fresh garlic pods — aromatic & flavourful", ...p(35,48), unit: "kg", quantity: "200g", imageUrl: BB + "10000114_19-fresho-garlic.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["spice","essential"], rating: 4.3, reviewCount: 2876 },
    { name: "Lady Finger (Bhindi)", description: "Tender lady fingers — great for frying & curries", ...p(35,48), unit: "kg", quantity: "500g", imageUrl: BB + "10000142_21-fresho-ladies-finger.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["fresh","daily"], rating: 4.2, reviewCount: 1876 },
    { name: "Bottle Gourd (Lauki)", description: "Light green bottle gourd — great for dal & kofta", ...p(28,38), unit: "pc", quantity: "1 pc", imageUrl: BB + "40053944_3-fresho-bottle-gourd-leafies-lauki-saag-organically-grown.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["fresh","light"], rating: 4.1, reviewCount: 1234 },
    { name: "Ridge Gourd (Turai)", description: "Fresh tender ridge gourd — low calorie & nutritious", ...p(25,35), unit: "kg", quantity: "500g", imageUrl: BB + "10000176_19-fresho-ridge-gourd.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["fresh","light"], rating: 4.0, reviewCount: 876 },
    { name: "Bitter Gourd (Karela)", description: "Fresh karela — known for health benefits", ...p(32,45), unit: "kg", quantity: "500g", imageUrl: BB + "10000048_24-fresho-bitter-gourd.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["healthy","medicinal"], rating: 3.9, reviewCount: 654 },
    { name: "Pointed Gourd (Parwal)", description: "Small green parwal — popular in Bengali cuisine", ...p(38,52), unit: "kg", quantity: "500g", imageUrl: BB + "40200394_1-farmland-frozen-vegetables-parwal.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["fresh","regional"], rating: 4.0, reviewCount: 543 },
    { name: "Raw Banana", description: "Green raw banana — perfect for chips & sabzi", ...p(22,30), unit: "kg", quantity: "500g", imageUrl: BB + "40225768_3-fresho-banana-nendran-raw.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["cooking","daily"], rating: 4.1, reviewCount: 987 },
    { name: "Drumstick (Moringa)", description: "Fresh drumsticks — rich in nutrients, great in sambar", ...p(35,48), unit: "pack", quantity: "250g", imageUrl: BB + "10000108_24-fresho-drumstickmoringa.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["nutritious","south-indian"], rating: 4.3, reviewCount: 1543 },
    { name: "Green Chilli", description: "Spicy green chillies — adds heat to any dish", ...p(15,22), unit: "pack", quantity: "100g", imageUrl: BB + "10000083_18-fresho-chilli-green-long-medium.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["spicy","essential"], rating: 4.3, reviewCount: 3210 },
    { name: "Coriander Leaves", description: "Fresh green dhaniya — aromatic garnish", ...p(12,18), unit: "bunch", quantity: "1 bunch", imageUrl: BB + "10000097_23-fresho-coriander-leaves.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["herb","garnish"], rating: 4.4, reviewCount: 4321 },
    { name: "Mint Leaves (Pudina)", description: "Fresh fragrant mint — perfect for chutney & raita", ...p(12,18), unit: "bunch", quantity: "1 bunch", imageUrl: BB + "10000137_21-fresho-mint-leaves-cleaned-without-roots.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["herb","garnish"], rating: 4.5, reviewCount: 3456 },
    { name: "Curry Leaves", description: "Aromatic curry patta — essential for South Indian cooking", ...p(10,15), unit: "bunch", quantity: "1 bunch", imageUrl: BB + "10000104_19-fresho-curry-leaves.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["herb","essential"], rating: 4.4, reviewCount: 2876 },
    { name: "Spring Onion", description: "Fresh spring onions with green stalks", ...p(18,25), unit: "bunch", quantity: "1 bunch", imageUrl: BB + "20000981_9-fresho-spring-onion-with-roots.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["fresh","garnish"], rating: 4.2, reviewCount: 1234 },
    { name: "Methi (Fenugreek Leaves)", description: "Fresh fenugreek leaves — great for parathas", ...p(15,22), unit: "bunch", quantity: "1 bunch", imageUrl: BB + "10000112_22-fresho-methiventhaya-keerai-cleaned-without-roots.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["leafy","iron-rich"], rating: 4.3, reviewCount: 1876 },
    { name: "Palak (Spinach)", description: "Iron-rich palak leaves — great for paneer & dal", ...p(20,28), unit: "bunch", quantity: "500g", imageUrl: BB + "20000979_14-fresho-palak-cleaned-without-roots.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["leafy","iron-rich","healthy"], rating: 4.4, reviewCount: 2345 },
    { name: "Tinda (Apple Gourd)", description: "Small round tinda — mild & easy to cook", ...p(28,38), unit: "kg", quantity: "500g", imageUrl: BB + "10000372_13-fresho-tinda.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["fresh","light"], rating: 4.0, reviewCount: 654 },
    { name: "Arbi (Colocasia)", description: "Fresh arbi roots — great for dry sabzi", ...p(45,60), unit: "kg", quantity: "500g", imageUrl: BB + "10000094_17-fresho-colocasia.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["root","traditional"], rating: 4.1, reviewCount: 876 },
    { name: "Raw Papaya", description: "Green raw papaya — for salads & sabzi", ...p(25,35), unit: "pc", quantity: "1 pc", imageUrl: BB + "40207215_3-fresho-papaya-raw.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["cooking","healthy"], rating: 4.0, reviewCount: 765 },
    { name: "Yam (Suran)", description: "Fresh yam — starchy & filling", ...p(40,55), unit: "kg", quantity: "500g", imageUrl: BB + "40099659_2-fresho-elephant-foot-yam-premium-institutional.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["root","protein"], rating: 4.0, reviewCount: 543 },
    { name: "Ivy Gourd (Kundru)", description: "Small green ivy gourd — crispy when stir-fried", ...p(30,42), unit: "kg", quantity: "250g", imageUrl: BB + "10000175_19-fresho-ridge-gourd.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["fresh","diabetes-friendly"], rating: 4.1, reviewCount: 432 },
    { name: "Cluster Beans (Gavar)", description: "Fresh cluster beans — high in fiber", ...p(35,48), unit: "kg", quantity: "250g", imageUrl: BB + "10000041_11-fresho-beans-cluster.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["fiber","healthy"], rating: 4.0, reviewCount: 543 },
    { name: "Amaranth Leaves (Lal Saag)", description: "Red amaranth leaves — iron-rich & nutritious", ...p(18,25), unit: "bunch", quantity: "1 bunch", imageUrl: BB + "30000575_17-fresho-amaranthus-red-cleaned-without-roots.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["leafy","superfood"], rating: 4.3, reviewCount: 876 },
  ],
  fruits: [
    { name: "Bananas", description: "Ripe Robusta bananas — naturally sweet & energy-rich", ...p(45,60), unit: "dozen", quantity: "12 pcs", imageUrl: BB + "10000025_32-fresho-banana-robusta.jpg", inStock: true, isFeatured: true, isOrganic: false, tags: ["daily","healthy"], rating: 4.6, reviewCount: 8765 },
    { name: "Red Apples", description: "Imported Red Delicious apples — crunchy & sweet", ...p(149,190), unit: "kg", quantity: "4 pcs", imageUrl: BB + "40116023_1-fresho-apple-red-delicious-large-institutional.jpg", inStock: true, isFeatured: true, isOrganic: false, tags: ["imported","premium"], rating: 4.5, reviewCount: 4321 },
    { name: "Alphonso Mangoes", description: "Premium Ratnagiri Alphonso — king of mangoes", ...p(299,399), unit: "kg", quantity: "12 pcs", imageUrl: BB + "30003344_23-fresho-alphonso-mango.jpg", inStock: true, isFeatured: true, isOrganic: false, tags: ["premium","seasonal"], rating: 4.8, reviewCount: 6543 },
    { name: "Watermelon", description: "Sweet Kiran watermelon — refreshing summer fruit", ...p(89,120), unit: "pc", quantity: "1 pc (2-3 kg)", imageUrl: BB + "10000207_26-fresho-watermelon-small.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["seasonal","refreshing"], rating: 4.3, reviewCount: 3456 },
    { name: "Strawberries", description: "Fresh Mahabaleshwar strawberries — sweet & tangy", ...p(99,149), unit: "pack", quantity: "250g", imageUrl: BB + "10000263_18-fresho-strawberry.jpg", inStock: true, isFeatured: true, isOrganic: true, tags: ["premium","organic"], rating: 4.7, reviewCount: 2345 },
    { name: "Oranges", description: "Nagpur Santra oranges — juicy & vitamin-C rich", ...p(69,89), unit: "kg", quantity: "6 pcs", imageUrl: BB + "10000266_40-fresho-orange-nagpur-regular.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["citrus","vitamin-c"], rating: 4.4, reviewCount: 3210 },
    { name: "Grapes - Green Seedless", description: "Thompson seedless green grapes — sweet & crisp", ...p(85,120), unit: "kg", quantity: "500g", imageUrl: BB + "40122445_6-fresho-grapes-green-residue-free.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["sweet"], rating: 4.5, reviewCount: 2678 },
    { name: "Pomegranate", description: "Ruby-red Bhagwa pomegranate — juicy & antioxidant-rich", ...p(99,139), unit: "kg", quantity: "3 pcs", imageUrl: BB + "10000269_37-fresho-pomegranate.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["healthy","antioxidant"], rating: 4.4, reviewCount: 1987 },
    { name: "Papaya", description: "Semi-ripe papaya — rich in enzymes & fiber", ...p(42,55), unit: "pc", quantity: "1 pc", imageUrl: BB + "10000152_24-fresho-papaya-medium.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["digestive"], rating: 4.2, reviewCount: 1543 },
    { name: "Kiwi - Imported", description: "New Zealand green kiwi — tangy & nutrient-dense", ...p(139,179), unit: "pack", quantity: "3 pcs", imageUrl: BB + "40086544_1-fresho-kiwi-berries-imported.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["imported","superfood"], rating: 4.5, reviewCount: 987 },
    { name: "Fresh Coconut", description: "Mature coconut — fresh & full of cream", ...p(35,45), unit: "pc", quantity: "1 pc", imageUrl: BB + "10000093_18-fresho-coconut-medium.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["traditional"], rating: 4.3, reviewCount: 2345 },
    { name: "Lemon", description: "Fresh lemons — tangy & zesty", ...p(29,39), unit: "pack", quantity: "6 pcs", imageUrl: BB + "40115970_2-fresho-lemon-premium-institutional.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["citrus","essential"], rating: 4.4, reviewCount: 4567 },
    { name: "Pineapple", description: "Sweet golden pineapple — rich in enzymes", ...p(59,79), unit: "pc", quantity: "1 pc", imageUrl: BB + "10000156_31-fresho-pineapple.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["tropical","enzyme"], rating: 4.3, reviewCount: 1876 },
    { name: "Guava - Thailand", description: "Crispy Thai guava — vitamin-C rich", ...p(69,89), unit: "kg", quantity: "4 pcs", imageUrl: BB + "30002322_16-fresho-guava-thai.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["vitamin-c","crispy"], rating: 4.4, reviewCount: 1543 },
    { name: "Chikoo (Sapota)", description: "Sweet brown sapota — soft & energy-rich", ...p(49,65), unit: "kg", quantity: "4 pcs", imageUrl: BB + "10000181_14-fresho-sapota.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["sweet","tropical"], rating: 4.2, reviewCount: 876 },
    { name: "Avocado - Imported", description: "Hass avocado — creamy & nutrient-dense superfood", ...p(149,199), unit: "pc", quantity: "1 pc", imageUrl: BB + "40259878_9-fresho-avocado-imported-ripe.jpg", inStock: true, isFeatured: true, isOrganic: false, tags: ["superfood","imported"], rating: 4.5, reviewCount: 2345 },
    { name: "Pear - Green", description: "Sweet & juicy green pears — imported", ...p(129,169), unit: "kg", quantity: "4 pcs", imageUrl: BB + "30000599_13-fresho-pear-green-indian.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["imported","sweet"], rating: 4.3, reviewCount: 987 },
    { name: "Green Apple", description: "Tart & crispy Granny Smith apples", ...p(169,219), unit: "kg", quantity: "4 pcs", imageUrl: BB + "40087359_3-fresho-green-apple-premium-institutional.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["tart","imported"], rating: 4.4, reviewCount: 1654 },
    { name: "Dragon Fruit", description: "Exotic pink dragon fruit — mild sweet flavour", ...p(89,129), unit: "pc", quantity: "1 pc", imageUrl: BB + "40008982_17-fresho-dragon-fruit.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["exotic","superfood"], rating: 4.3, reviewCount: 654 },
    { name: "Custard Apple (Sitaphal)", description: "Sweet creamy sitaphal — seasonal delight", ...p(79,109), unit: "kg", quantity: "500g", imageUrl: BB + "10000349_23-fresho-custard-apple.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["seasonal","sweet"], rating: 4.5, reviewCount: 876 },
    { name: "Sweet Lime (Mosambi)", description: "Juicy mosambi — mild sweet citrus", ...p(55,75), unit: "kg", quantity: "6 pcs", imageUrl: BB + "10000191_21-fresho-mosambi.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["citrus","juice"], rating: 4.3, reviewCount: 2345 },
    { name: "Plum - Imported", description: "Sweet dark plums — juicy & antioxidant-rich", ...p(119,159), unit: "pack", quantity: "500g", imageUrl: BB + "10000577_18-fresho-plum-imported.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["imported","antioxidant"], rating: 4.4, reviewCount: 765 },
    { name: "Litchi", description: "Fresh Muzaffarpur litchis — sweet & aromatic", ...p(99,139), unit: "kg", quantity: "500g", imageUrl: BB + "20001176_16-fresho-litchi.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["seasonal","premium"], rating: 4.6, reviewCount: 1543 },
    { name: "Fig (Anjeer) - Fresh", description: "Soft ripe figs — rich in calcium & fiber", ...p(129,179), unit: "pack", quantity: "4 pcs", imageUrl: BB + "30000466_18-fresho-fresh-figs.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["premium","superfood"], rating: 4.4, reviewCount: 543 },
    { name: "Black Grapes", description: "Seedless black grapes — sweet & antioxidant-rich", ...p(89,129), unit: "kg", quantity: "500g", imageUrl: BB + "40229414_6-fresho-grapes-black-imported.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["antioxidant"], rating: 4.5, reviewCount: 1876 },
    { name: "Muskmelon", description: "Sweet aromatic muskmelon — refreshing summer fruit", ...p(45,65), unit: "pc", quantity: "1 pc", imageUrl: BB + "10000141_27-fresho-muskmelon-netted-small.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["seasonal","refreshing"], rating: 4.3, reviewCount: 1234 },
    { name: "Jackfruit (Kathal)", description: "Fresh peeled jackfruit — meaty & versatile", ...p(69,95), unit: "pack", quantity: "500g", imageUrl: BB + "40100024_5-fresho-jackfruit-cut-raw.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["seasonal","protein"], rating: 4.2, reviewCount: 765 },
    { name: "Passion Fruit", description: "Tangy exotic passion fruit — great for juices", ...p(149,199), unit: "pack", quantity: "4 pcs", imageUrl: BB + "30000544_17-fresho-passion-fruit.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["exotic","imported"], rating: 4.3, reviewCount: 432 },
    { name: "Amla (Indian Gooseberry)", description: "Fresh amla — vitamin C powerhouse", ...p(35,49), unit: "kg", quantity: "250g", imageUrl: BB + "10000293_17-fresho-amla.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["superfood","immunity"], rating: 4.4, reviewCount: 1543 },
    { name: "Tender Coconut", description: "Fresh naariyal pani — natural electrolyte", ...p(45,60), unit: "pc", quantity: "1 pc", imageUrl: BB + "40288533_2-fresho-tender-coconut-untrimmed-andhra-boosts-overall-wellness.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["hydrating","natural"], rating: 4.5, reviewCount: 3210 },
    { name: "Dates - Fresh (Khajoor)", description: "Soft Medjool-style dates — naturally sweet", ...p(119,159), unit: "pack", quantity: "400g", imageUrl: BB + "30001109_11-fresho-fresh-dates-red.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["energy","natural-sweet"], rating: 4.6, reviewCount: 987 },
    { name: "Jamun (Java Plum)", description: "Purple jamun — tangy-sweet seasonal fruit", ...p(65,89), unit: "kg", quantity: "500g", imageUrl: BB + "30000992_6-fresho-jamun.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["seasonal","diabetes-friendly"], rating: 4.3, reviewCount: 876 },
    { name: "Peach - Imported", description: "Juicy ripe peaches — fuzzy & fragrant", ...p(139,179), unit: "pack", quantity: "4 pcs", imageUrl: BB + "30000547_1-fresho-peach-imported.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["imported","premium"], rating: 4.4, reviewCount: 654 },
  ],
  "dairy-eggs": [
    { name: "Amul Taaza Toned Milk", description: "Toned milk — 3% fat, pasteurized & homogenized", ...p(29,31), unit: "pack", quantity: "500 ml", imageUrl: BB + "148715_2-amul-toned-milk.jpg", inStock: true, isFeatured: true, isOrganic: false, tags: ["daily","fresh"], rating: 4.5, reviewCount: 12345 },
    { name: "Amul Gold Full Cream Milk", description: "Rich & creamy full cream milk — 6% fat", ...p(35,37), unit: "pack", quantity: "500 ml", imageUrl: BB + "40090893_8-amul-amul-gold.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["daily","premium"], rating: 4.6, reviewCount: 8765 },
    { name: "Mother Dairy Fresh Paneer", description: "Soft & fresh cottage cheese — high protein", ...p(89,105), unit: "pack", quantity: "200g", imageUrl: BB + "296470_7-mother-dairy-paneer-fresh.jpg", inStock: true, isFeatured: true, isOrganic: false, tags: ["protein","fresh"], rating: 4.4, reviewCount: 5678 },
    { name: "Amul Butter", description: "Pasteurized salted butter — perfect for toast", ...p(57,60), unit: "pack", quantity: "100g", imageUrl: BB + "104864_8-amul-butter-pasteurised.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["brand","staple"], rating: 4.7, reviewCount: 9876 },
    { name: "Epigamia Greek Yogurt - Strawberry", description: "Thick Greek yogurt with real strawberry", ...p(49,60), unit: "cup", quantity: "90g", imageUrl: BB + "40218838_2-epigamia-greek-yogurt-strawberry.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["probiotic","protein"], rating: 4.3, reviewCount: 3456 },
    { name: "Mother Dairy Dahi", description: "Set curd — naturally thick & creamy", ...p(42,48), unit: "pack", quantity: "400g", imageUrl: BB + "40004532_8-mother-dairy-dahi-made-from-toned-milk.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["probiotic","daily"], rating: 4.4, reviewCount: 6543 },
    { name: "Amul Cheese Slices", description: "Processed cheese slices — great for sandwiches", ...p(99,115), unit: "pack", quantity: "200g (10 slices)", imageUrl: BB + "104759_10-amul-cheese-slices.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["processed","convenient"], rating: 4.3, reviewCount: 4321 },
    { name: "Farm Fresh Eggs", description: "Brown farm eggs — protein-packed & fresh", ...p(75,89), unit: "pack", quantity: "6 pcs", imageUrl: BB + "40211595_4-eggoz-brown-farm-fresh-eggs-high-bio-available-protein-with-no-ddgs-hormone-or-steroids.jpg", inStock: true, isFeatured: true, isOrganic: true, tags: ["protein","farm-fresh"], rating: 4.5, reviewCount: 7654 },
    { name: "Country Eggs (Free Range)", description: "Free-range country eggs — rich yolk", ...p(89,110), unit: "pack", quantity: "6 pcs", imageUrl: BB + "40174310_1-backyard-country-chicken-eggs.jpg", inStock: true, isFeatured: false, isOrganic: true, tags: ["organic","free-range"], rating: 4.6, reviewCount: 2345 },
    { name: "Amul Fresh Cream", description: "Fresh dairy cream for cooking & toppings", ...p(39,45), unit: "pack", quantity: "200 ml", imageUrl: BB + "40102603_3-amul-fresh-cream-25-milk-fat-low-fat.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["cooking","fresh"], rating: 4.3, reviewCount: 3210 },
    { name: "Amul Masti Dahi (Curd)", description: "Thick & creamy dahi — rich probiotic culture", ...p(39,45), unit: "pack", quantity: "400g", imageUrl: BB + "40006925_7-amul-masti-dahi.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["daily","probiotic"], rating: 4.4, reviewCount: 8765 },
    { name: "Amul Mozzarella Cheese", description: "Pizza-grade mozzarella — melts perfectly", ...p(129,150), unit: "pack", quantity: "200g", imageUrl: BB + "40126254_4-amul-pizza-cheese-mozzarella-diced.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["cheese","pizza"], rating: 4.5, reviewCount: 3456 },
    { name: "Milky Mist Paneer - Premium", description: "Firm block paneer — ideal for tikka & curries", ...p(99,119), unit: "pack", quantity: "200g", imageUrl: BB + "40003150_5-milky-mist-paneer-premium-fresh.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["protein","premium"], rating: 4.4, reviewCount: 4321 },
    { name: "Yakult Probiotic Drink", description: "Probiotic culture drink — gut health", ...p(89,99), unit: "pack", quantity: "5 x 65 ml", imageUrl: BB + "292620_15-yakult-probiotic-health-drink.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["probiotic","healthy"], rating: 4.3, reviewCount: 5678 },
  ],
  snacks: [
    { name: "Lays Classic Salted", description: "Crunchy potato chips — classic salted flavor", ...p(20,25), unit: "pack", quantity: "52g", imageUrl: BB + "102741_19-lays-potato-chips-simple-classic-salted.jpg", inStock: true, isFeatured: true, isOrganic: false, tags: ["crunchy","classic"], rating: 4.4, reviewCount: 15678 },
    { name: "Kurkure Masala Munch", description: "Spicy puffed corn snack — desi taste", ...p(20,25), unit: "pack", quantity: "90g", imageUrl: BB + "40207351_7-kurkure-namkeen-masala-munch.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["spicy","indian"], rating: 4.3, reviewCount: 12345 },
    { name: "Haldirams Bhujia", description: "Classic Bikaner-style thin sev bhujia", ...p(60,80), unit: "pack", quantity: "400g", imageUrl: BB + "401772_3-haldirams-bhujia-sev.jpg", inStock: true, isFeatured: true, isOrganic: false, tags: ["traditional","namkeen"], rating: 4.6, reviewCount: 8765 },
    { name: "Roasted Peanuts - Masala", description: "Crunchy masala-roasted peanuts", ...p(45,60), unit: "pack", quantity: "300g", imageUrl: BB + "40268490_7-taali-roasted-peanuts-masala-rich-in-protein-delicious-crunchy.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["protein","snack"], rating: 4.4, reviewCount: 4321 },
    { name: "Dark Chocolate - 70% Cocoa", description: "Premium dark chocolate — rich & intense", ...p(149,199), unit: "bar", quantity: "100g", imageUrl: BB + "40051822_7-lindt-70-cocoa-dark.jpg", inStock: true, isFeatured: true, isOrganic: false, tags: ["premium","antioxidant"], rating: 4.7, reviewCount: 3456 },
    { name: "Digestive Biscuits", description: "High-fiber whole wheat digestive biscuits", ...p(55,70), unit: "pack", quantity: "200g", imageUrl: BB + "40023666_2-mcvities-digestive-biscuits-milk-chocolate-imported.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["fiber","healthy"], rating: 4.2, reviewCount: 5678 },
    { name: "Maggi Noodles", description: "2-minute instant masala noodles", ...p(14,18), unit: "pack", quantity: "70g", imageUrl: BB + "266160_27-maggi-masala-instant-noodles-vegetarian.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["instant","quick-cook"], rating: 4.5, reviewCount: 23456 },
    { name: "Almonds", description: "California premium almonds — crunchy & nutritious", ...p(299,399), unit: "pack", quantity: "200g", imageUrl: BB + "40274476_10-tata-sampann-100-pure-premium-california-almonds-whole-protein-rich.jpg", inStock: true, isFeatured: true, isOrganic: false, tags: ["premium","protein"], rating: 4.6, reviewCount: 6543 },
    { name: "Cashews - Whole", description: "Goa W320 whole cashews — creamy & delicious", ...p(349,449), unit: "pack", quantity: "200g", imageUrl: BB + "40231856_5-happilo-100-natural-premium-whole-cashews-value-pack.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["premium","dry-fruit"], rating: 4.5, reviewCount: 4321 },
    { name: "Oreo Chocolate Cookies", description: "Chocolate sandwich cookies with cream filling", ...p(30,35), unit: "pack", quantity: "120g", imageUrl: BB + "277584_50-cadbury-oreo-creme-biscuit-vanilla-original.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["cookies","fun"], rating: 4.4, reviewCount: 9876 },
    { name: "Britannia Good Day Butter", description: "Butter cookies with rich buttery taste", ...p(35,42), unit: "pack", quantity: "150g", imageUrl: BB + "40026357_14-britannia-good-day-butter-cookies.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["cookies","butter"], rating: 4.3, reviewCount: 7654 },
    { name: "Parle-G Gold", description: "Premium glucose biscuits — India's favourite", ...p(25,30), unit: "pack", quantity: "200g", imageUrl: BB + "20004285_13-parle-g-gold-gluco-biscuits.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["classic","budget"], rating: 4.5, reviewCount: 23456 },
    { name: "Pringles Original", description: "Stackable crispy potato chips — perfectly salted", ...p(99,129), unit: "can", quantity: "107g", imageUrl: BB + "1204073_12-pringles-potato-crisps-original.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["imported","crunchy"], rating: 4.4, reviewCount: 5678 },
    { name: "Trail Mix - Nutty Delight", description: "Mix of almonds, cashews, raisins & cranberries", ...p(199,249), unit: "pack", quantity: "200g", imageUrl: BB + "40229149_5-tasties-trail-mix-mixed-dry-fruits.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["healthy","snack"], rating: 4.5, reviewCount: 2345 },
    { name: "Makhana (Fox Nuts)", description: "Roasted makhana — light, crunchy & healthy snack", ...p(149,189), unit: "pack", quantity: "200g", imageUrl: BB + "40262211_3-mr-makhana-fox-nuts-black-salt-delicious-teatime-snack-popped-lotus-seeds-roasted-in-olive-oil.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["healthy","roasted"], rating: 4.4, reviewCount: 3456 },
    { name: "Aloo Bhujia", description: "Haldiram's potato sev — spicy & crispy", ...p(55,70), unit: "pack", quantity: "400g", imageUrl: BB + "40115851_8-tasties-namkeen-aloo-bhujia.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["namkeen","spicy"], rating: 4.3, reviewCount: 6543 },
    { name: "Cadbury Dairy Milk Silk", description: "Smooth & creamy milk chocolate bar", ...p(89,99), unit: "bar", quantity: "60g", imageUrl: BB + "100265001_55-cadbury-dairy-milk-silk-chocolate-bar.jpg", inStock: true, isFeatured: true, isOrganic: false, tags: ["chocolate","premium"], rating: 4.7, reviewCount: 15678 },
    { name: "Samosa - Frozen (Ready to Fry)", description: "Crispy aloo samosa — ready to deep fry", ...p(89,110), unit: "pack", quantity: "10 pcs", imageUrl: BB + "40267522_1-prasuma-spiced-aloo-mini-samosa-frozen.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["frozen","snack"], rating: 4.3, reviewCount: 2345 },
  ],
  beverages: [
    { name: "Real Fruit Power - Mixed Fruit", description: "100% fruit juice — no added sugar", ...p(99,125), unit: "pack", quantity: "1 litre", imageUrl: BB + "229922_13-real-fruit-power-juice-mixed.jpg", inStock: true, isFeatured: true, isOrganic: false, tags: ["juice","vitamin"], rating: 4.3, reviewCount: 6543 },
    { name: "Paper Boat Aam Panna", description: "Traditional raw mango drink — refreshing", ...p(30,40), unit: "pack", quantity: "200 ml", imageUrl: BB + "1209458_4-paper-boat-aam-panna-mango-drink.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["traditional","refreshing"], rating: 4.4, reviewCount: 4321 },
    { name: "Coca-Cola", description: "Classic cola refreshment — chilled & fizzy", ...p(40,45), unit: "bottle", quantity: "750 ml", imageUrl: BB + "251023_11-coca-cola-soft-drink-original-taste.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["fizzy","cold-drink"], rating: 4.2, reviewCount: 12345 },
    { name: "Bisleri Mineral Water", description: "Purified packaged drinking water", ...p(20,22), unit: "bottle", quantity: "1 litre", imageUrl: BB + "265876_2-bisleri-mineral-water.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["essential","daily"], rating: 4.1, reviewCount: 15678 },
    { name: "Tender Coconut Water", description: "100% natural tender coconut water — refreshing", ...p(40,55), unit: "pack", quantity: "200 ml", imageUrl: BB + "40300613_2-tender-coco-nut-tender-coconut-water-uht-processed-for-long-life.jpg", inStock: true, isFeatured: false, isOrganic: true, tags: ["natural","electrolyte"], rating: 4.5, reviewCount: 3456 },
    { name: "Tropicana Orange Juice", description: "100% orange juice — rich in Vitamin C", ...p(75,95), unit: "pack", quantity: "1 litre", imageUrl: BB + "229787_23-tropicana-100-orange-juice.jpg", inStock: true, isFeatured: true, isOrganic: false, tags: ["vitamin-c","breakfast"], rating: 4.4, reviewCount: 5678 },
    { name: "Lassi - Sweet", description: "Thick & creamy Punjab-style sweet lassi", ...p(35,45), unit: "cup", quantity: "200 ml", imageUrl: BB + "40004523_10-mother-dairy-lassi-sweetened-asli-refreshment.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["traditional","probiotic"], rating: 4.3, reviewCount: 2345 },
    { name: "Sprite", description: "Clear lemon-lime sparkling drink", ...p(40,45), unit: "bottle", quantity: "750 ml", imageUrl: BB + "251006_13-sprite-soft-drink-lime-flavoured.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["fizzy","lemon"], rating: 4.2, reviewCount: 8765 },
    { name: "Mango Lassi", description: "Thick & creamy mango flavored yogurt drink", ...p(45,55), unit: "cup", quantity: "200 ml", imageUrl: BB + "40307829_1-osam-mango-lassi.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["traditional","mango"], rating: 4.5, reviewCount: 3456 },
    { name: "Thandai Mix", description: "Ready-to-mix traditional thandai with dry fruits", ...p(149,189), unit: "jar", quantity: "250g", imageUrl: BB + "40298305_2-bansiwala-kesar-thandai-mix-traditional-indian-sweet.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["traditional","festive"], rating: 4.4, reviewCount: 1234 },
    { name: "Aam Panna Concentrate", description: "Raw mango drink concentrate — just add water", ...p(99,125), unit: "bottle", quantity: "500 ml", imageUrl: BB + "412401_6-paper-boat-aam-panna-mango-drink.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["summer","traditional"], rating: 4.3, reviewCount: 2345 },
    { name: "Fanta Orange", description: "Sparkling orange-flavored drink — refreshing", ...p(40,45), unit: "bottle", quantity: "750 ml", imageUrl: BB + "412247_1-fanta-orange.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["fizzy","orange"], rating: 4.1, reviewCount: 6543 },
    { name: "Amul Kool Badam Milk", description: "Almond flavored milk shake — chilled & creamy", ...p(25,30), unit: "pack", quantity: "200 ml", imageUrl: BB + "40175693_4-amul-kool-badam.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["milk","flavored"], rating: 4.3, reviewCount: 4321 },
  ],
  bakery: [
    { name: "Whole Wheat Bread", description: "Freshly baked 100% whole wheat bread", ...p(45,55), unit: "loaf", quantity: "400g", imageUrl: BB + "40162924_7-britannia-100-whole-wheat-bread.jpg", inStock: true, isFeatured: true, isOrganic: false, tags: ["whole-wheat","daily"], rating: 4.3, reviewCount: 7654 },
    { name: "Butter Croissants", description: "Flaky & buttery French-style croissants", ...p(79,99), unit: "pack", quantity: "4 pcs", imageUrl: BB + "900458480_1-unroll-all-butter-croissants-dough-sheet.jpg", inStock: true, isFeatured: true, isOrganic: false, tags: ["imported","premium"], rating: 4.5, reviewCount: 2345 },
    { name: "Sourdough Loaf", description: "Artisan sourdough bread — tangy & crusty", ...p(129,160), unit: "loaf", quantity: "600g", imageUrl: BB + "40285841_2-english-oven-whole-wheat-sourdough-stone-baked-bread-preservative-free.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["artisan","fermented"], rating: 4.6, reviewCount: 1234 },
    { name: "Muffins (Blueberry)", description: "Soft blueberry muffins — perfect tea-time snack", ...p(69,89), unit: "pack", quantity: "2 pcs", imageUrl: BB + "40337986_2-starbucks-coffee-blueberry-muffin.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["snack","sweet"], rating: 4.4, reviewCount: 1876 },
    { name: "Garlic Bread", description: "Pre-made garlic butter bread — just heat & eat", ...p(79,99), unit: "pack", quantity: "4 pcs", imageUrl: BB + "40200915_2-english-oven-garlic-bread.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["convenient","party"], rating: 4.3, reviewCount: 3456 },
    { name: "Pita Bread", description: "Soft Mediterranean pita pocket bread", ...p(55,70), unit: "pack", quantity: "6 pcs", imageUrl: BB + "40169961_3-the-bakers-dozen-pita-bread-100-wholewheat.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["mediterranean"], rating: 4.2, reviewCount: 987 },
    { name: "Chocolate Cake", description: "Rich Belgian chocolate layered cake", ...p(399,499), unit: "pc", quantity: "500g", imageUrl: BB + "40169307_3-foodpecker-chunky-chocolate-cake-pure-veg.jpg", inStock: true, isFeatured: true, isOrganic: false, tags: ["celebration","premium"], rating: 4.7, reviewCount: 4567 },
    { name: "Multigrain Bread", description: "7-grain nutritious bread — high fiber", ...p(55,69), unit: "loaf", quantity: "450g", imageUrl: BB + "40162930_5-britannia-multigrain-bread.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["healthy","multigrain"], rating: 4.4, reviewCount: 2345 },
    { name: "Garlic Bread - Frozen", description: "Ready-to-bake garlic bread with herbs & butter", ...p(89,110), unit: "pack", quantity: "300g", imageUrl: BB + "40117362_4-unroll-baguette-garlic-bread.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["frozen","party"], rating: 4.4, reviewCount: 3456 },
    { name: "Pav Buns", description: "Soft & fluffy pav buns — for pav bhaji & vada pav", ...p(35,42), unit: "pack", quantity: "6 pcs", imageUrl: BB + "40207188_2-paushtaa-whole-wheat-pau-buns.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["traditional","soft"], rating: 4.3, reviewCount: 5678 },
    { name: "Banana Muffins", description: "Moist banana walnut muffins — freshly baked", ...p(99,125), unit: "pack", quantity: "4 pcs", imageUrl: BB + "40174340_6-fresho-signature-banana-oats-cranberry-muffins.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["sweet","fresh"], rating: 4.4, reviewCount: 1234 },
    { name: "Butter Naan - Frozen", description: "Ready-to-heat butter naan — soft & fluffy", ...p(79,99), unit: "pack", quantity: "5 pcs", imageUrl: BB + "40124273_2-vadilal-quick-treat-frozen-food-naan-garlic-butter.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["frozen","ready-to-eat"], rating: 4.3, reviewCount: 2345 },
  ],
  "meat-fish": [
    { name: "Chicken Breast - Boneless", description: "Skinless boneless chicken breast — lean protein", ...p(249,320), unit: "pack", quantity: "500g", imageUrl: BB + "10000900_10-fresho-chicken-breast-boneless-antibiotic-residue-free-4-5-pcs.jpg", inStock: true, isFeatured: true, isOrganic: false, tags: ["protein","lean"], rating: 4.4, reviewCount: 5678 },
    { name: "Chicken Drumsticks", description: "Fresh chicken legs — skin-on, juicy", ...p(179,230), unit: "pack", quantity: "500g", imageUrl: BB + "20001220_4-starchik-chicken-drumsticks.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["fresh","popular"], rating: 4.5, reviewCount: 4321 },
    { name: "Chicken Keema", description: "Finely minced chicken — ready for kebabs & curries", ...p(219,280), unit: "pack", quantity: "500g", imageUrl: BB + "40096241_5-total-chicken-keema.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["minced","versatile"], rating: 4.3, reviewCount: 2345 },
    { name: "Rohu Fish - Cleaned", description: "River Rohu fish — cut & cleaned, ready to cook", ...p(199,260), unit: "pack", quantity: "500g", imageUrl: BB + "20000963_3-fresho-rohu-fish-large-curry-cutbengali-cut-preservative-free.jpg", inStock: true, isFeatured: true, isOrganic: false, tags: ["omega-3","fresh"], rating: 4.4, reviewCount: 3456 },
    { name: "Pomfret - Medium", description: "Silver pomfret — premium sea fish", ...p(449,550), unit: "pack", quantity: "2 pcs", imageUrl: BB + "155349_6-fresho-pomfret-white-large-preservative-free-6-8-pcs.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["premium","seafood"], rating: 4.6, reviewCount: 1987 },
    { name: "Prawns - Medium (Cleaned)", description: "Deveined & cleaned medium prawns", ...p(399,499), unit: "pack", quantity: "250g", imageUrl: BB + "40228232_1-megaa-small-prawns-fresh-juicy-cleaned.jpg", inStock: true, isFeatured: true, isOrganic: false, tags: ["seafood","premium"], rating: 4.5, reviewCount: 2345 },
    { name: "Mutton Curry Cut", description: "Fresh goat meat — bone-in curry cut pieces", ...p(599,720), unit: "pack", quantity: "500g", imageUrl: BB + "40048913_4-fresho-mutton-curry-cut-from-whole-carcass-8-10-pcs-antibiotic-residue-free-growth-hormone-free.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["premium","traditional"], rating: 4.5, reviewCount: 3456 },
    { name: "Eggs - Protein Plus", description: "Omega-3 enriched protein eggs", ...p(99,125), unit: "pack", quantity: "10 pcs", imageUrl: BB + "40208824_1-egg-first-first-protein-eggs.jpg", inStock: true, isFeatured: false, isOrganic: true, tags: ["omega-3","enriched"], rating: 4.4, reviewCount: 4567 },
  ],
  "grains-pulses": [
    { name: "India Gate Basmati Rice", description: "Premium aged basmati rice — long grain, aromatic", ...p(189,249), unit: "pack", quantity: "5 kg", imageUrl: BB + "190594_7-india-gate-basmati-rice-super.jpg", inStock: true, isFeatured: true, isOrganic: false, tags: ["premium","aromatic"], rating: 4.6, reviewCount: 8765 },
    { name: "Toor Dal (Arhar)", description: "Premium unpolished toor dal — cooks soft", ...p(119,149), unit: "pack", quantity: "1 kg", imageUrl: BB + "10000428_17-bb-popular-toorarhar-dal.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["protein","staple"], rating: 4.4, reviewCount: 5678 },
    { name: "Aashirvaad Whole Wheat Atta", description: "Chakki-fresh atta — soft rotis guaranteed", ...p(289,345), unit: "pack", quantity: "5 kg", imageUrl: BB + "126906_10-aashirvaad-atta-whole-wheat.jpg", inStock: true, isFeatured: true, isOrganic: false, tags: ["staple","daily"], rating: 4.5, reviewCount: 12345 },
    { name: "Moong Dal (Yellow)", description: "Split yellow moong dal — easy to digest", ...p(135,169), unit: "pack", quantity: "1 kg", imageUrl: BB + "30002287_11-tata-sampann-unpolished-moong-dal.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["protein","light"], rating: 4.3, reviewCount: 3456 },
    { name: "Chana Dal", description: "Split Bengal gram — nutty flavor for dals & sweets", ...p(99,125), unit: "pack", quantity: "1 kg", imageUrl: BB + "40159884_3-super-saver-chana-dal.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["protein","versatile"], rating: 4.3, reviewCount: 2345 },
    { name: "Rajma (Kidney Beans)", description: "Kashmiri rajma — large red kidney beans", ...p(139,175), unit: "pack", quantity: "1 kg", imageUrl: BB + "40267600_1-mayurank-jamoo-rajma-kidney-beans-high-in-protein.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["protein","punjabi"], rating: 4.4, reviewCount: 4321 },
    { name: "Oats", description: "Rolled whole grain oats — high fiber breakfast", ...p(89,110), unit: "pack", quantity: "1 kg", imageUrl: BB + "40003275_16-quaker-oats-breakfast-cereal-nutritious-rich-in-protein-dietary-fibre-easy-to-cook.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["healthy","breakfast"], rating: 4.5, reviewCount: 6543 },
    { name: "Sugar", description: "Refined white crystal sugar", ...p(45,52), unit: "pack", quantity: "1 kg", imageUrl: BB + "40019397_11-bb-popular-sugar.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["staple","daily"], rating: 4.2, reviewCount: 7654 },
    { name: "Poha (Flattened Rice)", description: "Medium-thick poha — perfect for breakfast", ...p(45,55), unit: "pack", quantity: "500g", imageUrl: BB + "40141775_6-jk-poha-flattened-rice.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["breakfast","traditional"], rating: 4.3, reviewCount: 3456 },
    { name: "Sooji (Rava/Semolina)", description: "Fine grain sooji — ideal for upma, halwa & rava dosa", ...p(39,48), unit: "pack", quantity: "500g", imageUrl: BB + "10000423_12-bb-royal-sooji-ordinarybombay-rava.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["breakfast","versatile"], rating: 4.3, reviewCount: 4321 },
    { name: "Maida (All Purpose Flour)", description: "Refined white flour — for naans, pastries & cakes", ...p(35,42), unit: "pack", quantity: "1 kg", imageUrl: BB + "10000416_13-bb-royal-maida.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["baking","staple"], rating: 4.1, reviewCount: 2345 },
    { name: "Besan (Gram Flour)", description: "Pure gram flour — for pakoras, kadhi & sweets", ...p(59,72), unit: "pack", quantity: "500g", imageUrl: BB + "40301045_7-aashirvaad-besan-flour-100-chana-dal.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["protein","versatile"], rating: 4.3, reviewCount: 3456 },
    { name: "Urad Dal (Black Gram)", description: "Whole urad dal — rich & creamy for dal makhani", ...p(119,145), unit: "pack", quantity: "1 kg", imageUrl: BB + "40135860_9-bb-royal-organic-urad-dal-black-split.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["protein","premium"], rating: 4.4, reviewCount: 2345 },
    { name: "Masoor Dal (Red Lentils)", description: "Quick-cooking red lentils — soft & nutritious", ...p(89,110), unit: "pack", quantity: "1 kg", imageUrl: BB + "20000435_16-bb-royal-masoor-dal.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["quick-cook","protein"], rating: 4.3, reviewCount: 3456 },
    { name: "Sona Masoori Rice", description: "Lightweight everyday rice — fluffy & aromatic", ...p(79,99), unit: "pack", quantity: "5 kg", imageUrl: BB + "40075896_7-bb-royal-sona-masoori-rice-raw-rice-super-premium.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["daily","south-indian"], rating: 4.4, reviewCount: 6543 },
    { name: "Organic Jaggery (Gur)", description: "Unrefined organic jaggery — natural sweetener", ...p(69,85), unit: "pack", quantity: "500g", imageUrl: BB + "40222536_9-organic-india-organic-jaggery-powder-healthy-sugar-substitute.jpg", inStock: true, isFeatured: false, isOrganic: true, tags: ["organic","natural"], rating: 4.4, reviewCount: 1876 },
    { name: "Soya Chunks", description: "High-protein soya nuggets — meat alternative", ...p(79,99), unit: "pack", quantity: "1 kg", imageUrl: BB + "257382_9-nutrela-soya-chunks.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["protein","vegetarian"], rating: 4.3, reviewCount: 4321 },
    { name: "Pasta - Penne", description: "Durum wheat penne pasta — Italian quality", ...p(69,85), unit: "pack", quantity: "500g", imageUrl: BB + "40118006_6-food-craft-pasta-penne.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["italian","instant"], rating: 4.2, reviewCount: 2345 },
  ],
  "spices-masala": [
    { name: "Turmeric Powder", description: "Pure haldi powder — vibrant color & earthy flavor", ...p(55,70), unit: "pack", quantity: "200g", imageUrl: BB + "40075125_10-bb-royal-organic-turmeric-powder.jpg", inStock: true, isFeatured: true, isOrganic: false, tags: ["essential","daily"], rating: 4.5, reviewCount: 6543 },
    { name: "Red Chili Powder", description: "Guntur red chili powder — hot & flavorful", ...p(65,85), unit: "pack", quantity: "200g", imageUrl: BB + "284304_4-catch-red-chillilal-mirch-powder.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["spicy","essential"], rating: 4.4, reviewCount: 5432 },
    { name: "Cumin Seeds (Jeera)", description: "Whole cumin seeds — aromatic & essential", ...p(89,110), unit: "pack", quantity: "200g", imageUrl: BB + "413434_2-jk-jeeracumin-seed.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["whole-spice","essential"], rating: 4.5, reviewCount: 4321 },
    { name: "Coriander Powder", description: "Fresh ground coriander powder — mild & citrusy", ...p(49,62), unit: "pack", quantity: "200g", imageUrl: BB + "40169657_5-kitchen-treasures-coriander-powder.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["essential","mild"], rating: 4.3, reviewCount: 3456 },
    { name: "Garam Masala", description: "Aromatic blend of whole spices — premium quality", ...p(79,99), unit: "pack", quantity: "100g", imageUrl: BB + "30006818_3-catch-super-garam-masala.jpg", inStock: true, isFeatured: true, isOrganic: false, tags: ["blend","premium"], rating: 4.6, reviewCount: 5678 },
    { name: "Kitchen King Masala", description: "All-purpose vegetable masala mix", ...p(55,69), unit: "pack", quantity: "100g", imageUrl: BB + "40128825_3-everest-masala-kitchen-king.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["blend","versatile"], rating: 4.4, reviewCount: 4321 },
    { name: "Black Pepper Whole", description: "Malabar whole black pepper — bold & pungent", ...p(99,125), unit: "pack", quantity: "100g", imageUrl: BB + "30006836_2-catch-black-pepper.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["whole-spice","premium"], rating: 4.5, reviewCount: 2345 },
    { name: "Iodised Salt", description: "Tata iodised salt — essential for every kitchen", ...p(24,27), unit: "pack", quantity: "1 kg", imageUrl: BB + "40288919_7-table-top-refined-iodised-salt-rich-in-iron.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["essential","daily"], rating: 4.4, reviewCount: 12345 },
  ],
  "oil-ghee": [
    { name: "Fortune Sunflower Oil", description: "Refined sunflower oil — light & heart-healthy", ...p(149,175), unit: "bottle", quantity: "1 litre", imageUrl: BB + "274145_17-fortune-sun-lite-sunflower-refined-oil.jpg", inStock: true, isFeatured: true, isOrganic: false, tags: ["cooking","heart-healthy"], rating: 4.4, reviewCount: 8765 },
    { name: "Saffola Gold Oil", description: "Blended cooking oil — good for heart", ...p(179,210), unit: "bottle", quantity: "1 litre", imageUrl: BB + "147491_11-saffola-gold-refined-cooking-oil-blended-rice-bran-sunflower-oil-helps-keeps-heart-healthy.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["healthy","premium"], rating: 4.5, reviewCount: 6543 },
    { name: "Amul Cow Ghee", description: "Pure cow ghee — made from fresh cream", ...p(549,649), unit: "jar", quantity: "500 ml", imageUrl: BB + "40046230_4-amul-amul-cow-ghee-1-l.jpg", inStock: true, isFeatured: true, isOrganic: false, tags: ["pure","traditional"], rating: 4.7, reviewCount: 9876 },
    { name: "Mustard Oil - Kachi Ghani", description: "Cold-pressed mustard oil — pungent & flavorful", ...p(165,195), unit: "bottle", quantity: "1 litre", imageUrl: BB + "40211106_1-kanodia-kolhu-brand-mustard-oil-kachi-ghani.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["cold-pressed","traditional"], rating: 4.3, reviewCount: 4321 },
    { name: "Extra Virgin Olive Oil", description: "Imported cold-pressed olive oil — premium quality", ...p(449,550), unit: "bottle", quantity: "500 ml", imageUrl: BB + "40006250_7-borges-extra-virgin-olive-oil.jpg", inStock: true, isFeatured: false, isOrganic: true, tags: ["imported","premium"], rating: 4.6, reviewCount: 2345 },
    { name: "Coconut Oil", description: "Virgin cold-pressed coconut oil — versatile", ...p(199,249), unit: "bottle", quantity: "500 ml", imageUrl: BB + "40308516_2-nuts-for-us-pvt-ltd-pure-coconut-oil-cold-pressed.jpg", inStock: true, isFeatured: false, isOrganic: true, tags: ["organic","cold-pressed"], rating: 4.5, reviewCount: 3456 },
  ],
  "dry-fruits": [
    { name: "California Almonds", description: "Premium California almonds — crunchy & nutritious", ...p(299,399), unit: "pack", quantity: "200g", imageUrl: BB + "40274476_10-tata-sampann-100-pure-premium-california-almonds-whole-protein-rich.jpg", inStock: true, isFeatured: true, isOrganic: false, tags: ["premium","protein"], rating: 4.6, reviewCount: 7654 },
    { name: "Cashews W320", description: "Goa whole cashews — creamy & buttery", ...p(349,449), unit: "pack", quantity: "200g", imageUrl: BB + "40142880_4-regency-cashew-w320.jpg", inStock: true, isFeatured: true, isOrganic: false, tags: ["premium","whole"], rating: 4.5, reviewCount: 5432 },
    { name: "Walnuts - Halves", description: "Kashmir walnut halves — brain food", ...p(399,499), unit: "pack", quantity: "200g", imageUrl: BB + "40312695_1-wonderland-foods-california-in-shell-walnut-100-natural.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["brain-food","omega-3"], rating: 4.5, reviewCount: 3456 },
    { name: "Pistachios - Roasted Salted", description: "Iranian roasted & salted pistachios", ...p(399,499), unit: "pack", quantity: "200g", imageUrl: BB + "40037449_4-delight-nuts-roasted-salted-pistachios.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["roasted","premium"], rating: 4.6, reviewCount: 4321 },
    { name: "Raisins (Kishmish)", description: "Afghan green raisins — sweet & plump", ...p(149,189), unit: "pack", quantity: "250g", imageUrl: BB + "40234316_2-super-saver-raisinskishmish-indian.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["iron-rich","sweet"], rating: 4.4, reviewCount: 2345 },
    { name: "Dates - Medjool", description: "Large Medjool dates — soft, sweet & caramel-like", ...p(399,499), unit: "pack", quantity: "250g", imageUrl: BB + "40266318_6-bb-royal-dates-medjool.jpg", inStock: true, isFeatured: true, isOrganic: true, tags: ["premium","natural-sweetener"], rating: 4.7, reviewCount: 1987 },
    { name: "Mixed Dry Fruits", description: "Premium assorted dry fruits & nuts mix", ...p(449,599), unit: "box", quantity: "250g", imageUrl: BB + "40229149_5-tasties-trail-mix-mixed-dry-fruits.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["gift","assorted"], rating: 4.5, reviewCount: 3456 },
    { name: "Pure Honey", description: "Raw unprocessed honey — natural sweetener", ...p(299,375), unit: "jar", quantity: "500g", imageUrl: BB + "202277_11-dabur-100-pure-honey-worlds-no1-honey-brand-with-no-sugar-adulteration.jpg", inStock: true, isFeatured: true, isOrganic: true, tags: ["natural","organic"], rating: 4.6, reviewCount: 5678 },
  ],
  "tea-coffee": [
    { name: "Tata Tea Gold", description: "Premium assam blend — strong & aromatic", ...p(225,270), unit: "pack", quantity: "500g", imageUrl: BB + "263642_22-tata-tea-gold-tea.jpg", inStock: true, isFeatured: true, isOrganic: false, tags: ["daily","strong"], rating: 4.5, reviewCount: 12345 },
    { name: "Lipton Green Tea - Honey Lemon", description: "Green tea bags with honey lemon flavor", ...p(175,210), unit: "box", quantity: "25 bags", imageUrl: BB + "1201451_2-lipton-green-tea-honey-lemon.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["healthy","antioxidant"], rating: 4.3, reviewCount: 4321 },
    { name: "Nescafe Classic Coffee", description: "100% pure instant coffee — rich aroma", ...p(249,299), unit: "jar", quantity: "100g", imageUrl: BB + "231187_13-nescafe-classic-100-pure-instant-coffee.jpg", inStock: true, isFeatured: true, isOrganic: false, tags: ["instant","aromatic"], rating: 4.6, reviewCount: 9876 },
    { name: "Bru Instant Coffee", description: "Smooth instant coffee — perfect morning brew", ...p(199,240), unit: "jar", quantity: "100g", imageUrl: BB + "266531_22-bru-instant-coffee.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["instant","smooth"], rating: 4.4, reviewCount: 6543 },
    { name: "Organic India Tulsi Green Tea", description: "Tulsi infused green tea — stress relief", ...p(199,249), unit: "box", quantity: "25 bags", imageUrl: BB + "40223290_4-organic-india-tulsi-green-tea-ashwagandha-stress-relieving-refreshing.jpg", inStock: true, isFeatured: false, isOrganic: true, tags: ["organic","wellness"], rating: 4.5, reviewCount: 3456 },
    { name: "Taj Mahal Tea", description: "Brooke Bond Taj Mahal — rich & flavourful", ...p(280,340), unit: "pack", quantity: "500g", imageUrl: BB + "266551_14-taj-mahal-tea.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["premium","aromatic"], rating: 4.6, reviewCount: 7654 },
  ],
  cleaning: [
    { name: "Surf Excel Matic Liquid", description: "Top-load washing machine liquid detergent", ...p(249,299), unit: "bottle", quantity: "1 litre", imageUrl: BB + "40130610_12-surf-excel-detergent-liquid-matic-front-load.jpg", inStock: true, isFeatured: true, isOrganic: false, tags: ["laundry","matic"], rating: 4.4, reviewCount: 8765 },
    { name: "Vim Dishwash Gel - Lemon", description: "Concentrated dishwash gel — tough on grease", ...p(99,125), unit: "bottle", quantity: "500 ml", imageUrl: BB + "266958_14-vim-dishwash-liquid-gel-lemon.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["kitchen","lemon"], rating: 4.3, reviewCount: 6543 },
    { name: "Harpic Toilet Cleaner", description: "Powerful toilet cleaning liquid — kills 99.9% germs", ...p(89,110), unit: "bottle", quantity: "500 ml", imageUrl: BB + "1200277_21-harpic-disinfectant-toilet-cleaner-liquid-original-kills-999-germs.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["bathroom","disinfectant"], rating: 4.2, reviewCount: 5432 },
    { name: "Lizol Floor Cleaner - Citrus", description: "Disinfectant floor cleaner — fresh citrus scent", ...p(139,170), unit: "bottle", quantity: "975 ml", imageUrl: BB + "249154_17-lizol-disinfectant-surface-floor-cleaner-liquid-citrus-kills-999-germs.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["floor","disinfectant"], rating: 4.3, reviewCount: 4321 },
    { name: "Colin Glass Cleaner", description: "Streak-free glass & surface cleaner", ...p(89,110), unit: "spray", quantity: "500 ml", imageUrl: BB + "40005088_2-colin-glass-cleaner-lemon-fragrance-2x-more-shine-with-shine-boosters.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["glass","spray"], rating: 4.2, reviewCount: 3456 },
    { name: "Garbage Bags - Large", description: "Oxo-biodegradable garbage bags — 19x21 inch", ...p(99,125), unit: "roll", quantity: "30 bags", imageUrl: BB + "40137711_18-bb-home-oxo-biodegradable-garbage-bag-large-blue.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["essential","eco"], rating: 4.1, reviewCount: 2345 },
    { name: "Scotch-Brite Scrub Pad", description: "Heavy-duty kitchen scrub pad — tough on grease", ...p(25,30), unit: "pc", quantity: "1 pc", imageUrl: BB + "40008474_8-scotch-brite-scrub-pad-large.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["kitchen","essential"], rating: 4.2, reviewCount: 3456 },
    { name: "Odonil Air Freshener", description: "Bathroom air freshener — long-lasting fragrance", ...p(69,85), unit: "block", quantity: "50g", imageUrl: BB + "40251025_2-odonil-air-freshener-mystic-rose-removes-odour-for-bathroom.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["bathroom","fragrance"], rating: 4.1, reviewCount: 2345 },
    { name: "Facial Tissues - Box", description: "Soft 2-ply facial tissues — gentle on skin", ...p(89,110), unit: "box", quantity: "100 pulls", imageUrl: BB + "40132310_8-bb-home-facial-tissues-box-2-ply-100-virgin-pulppaper.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["essential","soft"], rating: 4.2, reviewCount: 1876 },
    { name: "Kitchen Paper Towel Roll", description: "Super absorbent kitchen towel — 2-ply", ...p(99,125), unit: "roll", quantity: "2 rolls", imageUrl: BB + "40255953_2-10on-tissues-soft-kitchen-tissue-paper-rolls-2-ply-highly-absorbent-230-x-225-cm-2-in-1-pack.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["kitchen","absorbent"], rating: 4.3, reviewCount: 2345 },
  ],
  "personal-care": [
    { name: "Dettol Handwash - Original", description: "Antibacterial liquid handwash — kills 99.9% germs", ...p(99,120), unit: "pump", quantity: "200 ml", imageUrl: BB + "1202458_9-dettol-handwash-original.jpg", inStock: true, isFeatured: true, isOrganic: false, tags: ["hygiene","antibacterial"], rating: 4.4, reviewCount: 9876 },
    { name: "Dove Shampoo - Daily Shine", description: "Nourishing shampoo for smooth & shiny hair", ...p(199,240), unit: "bottle", quantity: "340 ml", imageUrl: BB + "1219157_1-dove-shampoo-daily-shine.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["hair-care","shine"], rating: 4.3, reviewCount: 6543 },
    { name: "Colgate MaxFresh Toothpaste", description: "Cooling crystal toothpaste — fresh breath", ...p(99,120), unit: "tube", quantity: "150g", imageUrl: BB + "40195547_11-colgate-maxfresh-toothpaste-blue-gel-with-menthol-for-super-fresh-breath-peppermint-ice.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["oral-care","fresh"], rating: 4.4, reviewCount: 12345 },
    { name: "Nivea Body Lotion", description: "Deep moisture body lotion — 48hr hydration", ...p(249,299), unit: "bottle", quantity: "400 ml", imageUrl: BB + "40102048_11-nivea-body-lotion-for-very-dry-skin-nourishing-body-milk-with-2x-almond-oil-for-men-women.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["skin-care","moisturizer"], rating: 4.5, reviewCount: 5678 },
    { name: "Lux Soap Bar - Rose", description: "Soft & smooth skin with rose fragrance", ...p(35,42), unit: "bar", quantity: "75g", imageUrl: BB + "276959_12-lux-beauty-soap-for-glowing-skin-rose-vitamin-e-mega.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["soap","fragrant"], rating: 4.2, reviewCount: 8765 },
    { name: "Whisper Ultra Clean Pads", description: "Ultra-thin sanitary pads — dry-feel technology", ...p(169,199), unit: "pack", quantity: "30 pads", imageUrl: BB + "40252521_2-whisper-ultra-clean-sanitary-pads-for-women-x-large-with-dual-action-gel-for-absorption-delightful-scent.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["feminine","hygiene"], rating: 4.3, reviewCount: 7654 },
    { name: "Himalaya Neem Face Wash", description: "Purifying neem face wash — controls oily skin", ...p(149,179), unit: "tube", quantity: "150 ml", imageUrl: BB + "40093649_4-himalaya-men-pimple-clear-neem-face-wash.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["face","neem"], rating: 4.3, reviewCount: 5678 },
    { name: "Fogg Deodorant - Marco", description: "Long-lasting fragrance deodorant spray — no gas", ...p(189,229), unit: "spray", quantity: "120 ml", imageUrl: BB + "40248611_1-fogg-deodorant-body-spray-one-winner-long-lasting-freshness-dense-fragrance-for-men.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["fragrance","men"], rating: 4.2, reviewCount: 4321 },
    { name: "Vaseline Body Lotion - Cocoa", description: "Intensive care cocoa glow body lotion", ...p(199,249), unit: "bottle", quantity: "400 ml", imageUrl: BB + "40118800_30-vaseline-intensive-care-deep-moisture-body-lotion.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["skin-care","cocoa"], rating: 4.4, reviewCount: 3456 },
    { name: "Gillette Mach3 Razor", description: "3-blade precision razor — close shave", ...p(299,399), unit: "pack", quantity: "1 razor + 1 blade", imageUrl: BB + "263494_13-gillette-mach3-manual-shaving-razor-blades-cartridge.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["shaving","men"], rating: 4.4, reviewCount: 2345 },
  ],
  "frozen-foods": [
    { name: "McCain French Fries", description: "Crispy golden French fries — just fry & serve", ...p(135,169), unit: "pack", quantity: "450g", imageUrl: BB + "30000369_10-mccain-french-fries.jpg", inStock: true, isFeatured: true, isOrganic: false, tags: ["snack","party"], rating: 4.4, reviewCount: 6543 },
    { name: "ITC Master Chef Chicken Nuggets", description: "Crispy chicken nuggets — ready to cook", ...p(199,250), unit: "pack", quantity: "450g", imageUrl: BB + "1207206_4-itc-master-chef-chicken-nuggets-crunchy-450-gm-cheesy-corn-triangles-320-gm.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["snack","chicken"], rating: 4.3, reviewCount: 4321 },
    { name: "Frozen Green Peas", description: "IQF garden peas — locked-in freshness", ...p(79,99), unit: "pack", quantity: "500g", imageUrl: BB + "103692_2-safal-frozen-green-peas.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["vegetable","convenient"], rating: 4.2, reviewCount: 3456 },
    { name: "Amul Ice Cream - Vanilla", description: "Rich & creamy vanilla ice cream tub", ...p(249,299), unit: "tub", quantity: "1 litre", imageUrl: BB + "1223291_0-amul-ice-cream-vanilla-magic-real-milk.jpg", inStock: true, isFeatured: true, isOrganic: false, tags: ["dessert","cream"], rating: 4.6, reviewCount: 8765 },
    { name: "Frozen Paratha (Malabar)", description: "Layered Malabar paratha — flaky & soft", ...p(99,125), unit: "pack", quantity: "5 pcs", imageUrl: BB + "40282384_4-aashirvaad-malabar-paratha-ready-to-cook-frozen-no-added-preservatives.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["breakfast","ready-to-cook"], rating: 4.4, reviewCount: 5678 },
    { name: "Frozen Sweet Corn", description: "Sweet corn kernels — convenient & fresh", ...p(69,89), unit: "pack", quantity: "500g", imageUrl: BB + "185568_2-safal-frozen-sweet-corn.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["vegetable","versatile"], rating: 4.3, reviewCount: 2345 },
  ],
  "baby-care": [
    { name: "Pampers Diapers - Medium", description: "Baby-dry diapers — up to 12 hours dryness", ...p(699,849), unit: "pack", quantity: "66 pcs", imageUrl: BB + "20004778_12-pampers-active-baby-diapers-new-born.jpg", inStock: true, isFeatured: true, isOrganic: false, tags: ["diapers","premium"], rating: 4.5, reviewCount: 9876 },
    { name: "Cerelac Wheat Stage 1", description: "Nestle Cerelac baby food — enriched with iron", ...p(265,310), unit: "box", quantity: "300g", imageUrl: BB + "240178_13-nestle-cerelac-baby-cereal-with-milk-wheat-from-6-12-months-rich-in-iron.jpg", inStock: true, isFeatured: true, isOrganic: false, tags: ["baby-food","nutritious"], rating: 4.4, reviewCount: 6543 },
    { name: "Johnson's Baby Shampoo", description: "Gentle no-tears baby shampoo", ...p(189,225), unit: "bottle", quantity: "200 ml", imageUrl: BB + "262921_18-johnsons-baby-no-more-tears-baby-shampoo.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["gentle","no-tears"], rating: 4.6, reviewCount: 7654 },
    { name: "Himalaya Baby Lotion", description: "Gentle moisturizing lotion for baby's soft skin", ...p(149,179), unit: "bottle", quantity: "200 ml", imageUrl: BB + "20002821_5-himalaya-baby-baby-lotion.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["herbal","gentle"], rating: 4.5, reviewCount: 4321 },
    { name: "Baby Wet Wipes", description: "Gentle alcohol-free baby wipes — 80 pulls", ...p(149,179), unit: "pack", quantity: "80 wipes", imageUrl: BB + "40022149_11-mee-mee-baby-wet-wipes-lemon-fragrance.jpg", inStock: true, isFeatured: false, isOrganic: false, tags: ["wipes","gentle"], rating: 4.3, reviewCount: 5678 },
  ],
};

export function getBBProductsForCategory(categorySlug: string): BBProduct[] {
  return BB_PRODUCTS[categorySlug] || [];
}

export function getAllBBCategories(): BBCategory[] {
  return BB_CATEGORIES;
}

export function getAllBBProducts(): { category: BBCategory; products: BBProduct[] }[] {
  return BB_CATEGORIES.map(cat => ({
    category: cat,
    products: BB_PRODUCTS[cat.slug] || [],
  })).filter(entry => entry.products.length > 0);
}
