export interface ProduceItem {
  name: string;
  description: string;
  price: number;
  unit: string;
  quantity: string;
  categoryId: number;
  categoryName: string;
  variants: string[];
  rating: number;
  reviewCount: number;
  tags: string[];
  isOrganic?: boolean;
}

export const PRODUCE_DATA: ProduceItem[] = [
  // ───── VEGETABLES (17) ─────
  { name: "Fresh Tomatoes", price: 30, unit: "kg", quantity: "1 kg", categoryId: 17, categoryName: "Vegetables", variants: ["250g", "500g", "1 kg"], description: "Farm-fresh tomatoes, rich in vitamins and antioxidants. Perfect for curries, salads, and chutneys.", rating: 4.3, reviewCount: 3421, tags: ["vegetable", "tomato"] },
  { name: "Onion", price: 30, unit: "kg", quantity: "1 kg", categoryId: 17, categoryName: "Vegetables", variants: ["250g", "500g", "1 kg"], description: "Red onions, an essential ingredient for Indian cooking. Adds flavor and depth to every dish.", rating: 4.4, reviewCount: 5678, tags: ["vegetable", "onion"] },
  { name: "Potato", price: 25, unit: "kg", quantity: "1 kg", categoryId: 17, categoryName: "Vegetables", variants: ["250g", "500g", "1 kg"], description: "Fresh potatoes, a kitchen staple. Versatile for curries, fries, and snacks.", rating: 4.3, reviewCount: 4321, tags: ["vegetable", "potato"] },
  { name: "Green Capsicum", price: 45, unit: "kg", quantity: "1 kg", categoryId: 17, categoryName: "Vegetables", variants: ["250g", "500g", "1 kg"], description: "Crisp green capsicums (shimla mirch) perfect for stir-fries, salads, and curries.", rating: 4.1, reviewCount: 1234, tags: ["vegetable", "capsicum"] },
  { name: "Lady Finger", price: 35, unit: "kg", quantity: "1 kg", categoryId: 17, categoryName: "Vegetables", variants: ["250g", "500g", "1 kg"], description: "Tender lady fingers (bhindi), ideal for sabzi and stir-fries. A summer favorite.", rating: 4.2, reviewCount: 2156, tags: ["vegetable", "bhindi", "okra"] },
  { name: "Cauliflower", price: 35, unit: "pc", quantity: "1 pc", categoryId: 17, categoryName: "Vegetables", variants: [], description: "Fresh white cauliflower (phool gobhi), perfect for gobi sabzi, aloo gobi, and biryanis.", rating: 4.1, reviewCount: 1876, tags: ["vegetable", "cauliflower"] },
  { name: "Brinjal", price: 30, unit: "kg", quantity: "1 kg", categoryId: 17, categoryName: "Vegetables", variants: ["250g", "500g", "1 kg"], description: "Fresh brinjal (eggplant / baingan), great for bharwa baingan and curries.", rating: 4.0, reviewCount: 987, tags: ["vegetable", "brinjal", "baingan", "eggplant"] },
  { name: "Sweet Corn", price: 25, unit: "pc", quantity: "1 pc", categoryId: 17, categoryName: "Vegetables", variants: [], description: "Fresh sweet corn cobs (makka), perfect for snacking, soups, and salads.", rating: 4.3, reviewCount: 1543, tags: ["vegetable", "corn", "makka"] },
  { name: "Green Chilli", price: 40, unit: "kg", quantity: "1 kg", categoryId: 17, categoryName: "Vegetables", variants: ["100g", "250g", "500g"], description: "Fresh green chillies, adds the perfect kick to any Indian dish.", rating: 4.2, reviewCount: 876, tags: ["vegetable", "chilli", "spice"] },
  { name: "Green Peas", price: 80, unit: "kg", quantity: "1 kg", categoryId: 17, categoryName: "Vegetables", variants: ["250g", "500g", "1 kg"], description: "Fresh green peas (matar), sweet and tender. Great for curries, rice, and salads.", rating: 4.4, reviewCount: 2341, tags: ["vegetable", "peas", "matar"] },

  // ───── LEAFY VEGETABLES (33) ─────
  { name: "Spinach", price: 20, unit: "kg", quantity: "500g", categoryId: 33, categoryName: "Leafy Vegetables", variants: ["250g", "500g", "1 kg"], description: "Fresh spinach leaves (palak), rich in iron and vitamins. Perfect for palak paneer and dal.", rating: 4.3, reviewCount: 2134, tags: ["leafy", "spinach", "palak"] },
  { name: "Fenugreek Leaves", price: 20, unit: "kg", quantity: "500g", categoryId: 33, categoryName: "Leafy Vegetables", variants: ["250g", "500g"], description: "Fresh methi leaves, slightly bitter and aromatic. Great for methi paratha and dal methi.", rating: 4.1, reviewCount: 876, tags: ["leafy", "methi", "fenugreek"] },
  { name: "Coriander", price: 15, unit: "bunch", quantity: "1 bunch", categoryId: 33, categoryName: "Leafy Vegetables", variants: [], description: "Fresh coriander leaves (dhania), the essential garnish for all Indian dishes.", rating: 4.5, reviewCount: 5123, tags: ["leafy", "coriander", "dhania"] },
  { name: "Curry Leaves", price: 20, unit: "bunch", quantity: "1 bunch", categoryId: 33, categoryName: "Leafy Vegetables", variants: [], description: "Aromatic curry leaves (kadi patta), essential for tempering in South Indian and Maharashtrian cooking.", rating: 4.4, reviewCount: 3421, tags: ["leafy", "curry leaves", "kadi patta"] },
  { name: "Cabbage", price: 20, unit: "kg", quantity: "1 kg", categoryId: 33, categoryName: "Leafy Vegetables", variants: ["500g", "1 kg"], description: "Fresh green cabbage (patta gobhi), perfect for salads, stir-fries, and coleslaw.", rating: 4.0, reviewCount: 1234, tags: ["leafy", "cabbage"] },
  { name: "Fresh Mint", price: 15, unit: "bunch", quantity: "1 bunch", categoryId: 33, categoryName: "Leafy Vegetables", variants: [], description: "Fragrant mint leaves (pudina), perfect for chutneys, raita, and cooling drinks.", rating: 4.4, reviewCount: 2341, tags: ["leafy", "mint", "pudina"] },
  { name: "Dill Leaves", price: 15, unit: "bunch", quantity: "1 bunch", categoryId: 33, categoryName: "Leafy Vegetables", variants: [], description: "Fresh dill (suva bhaji), aromatic herb perfect for dal, fish dishes, and salads.", rating: 4.1, reviewCount: 654, tags: ["leafy", "dill", "suva"] },
  { name: "Mustard Greens", price: 20, unit: "kg", quantity: "500g", categoryId: 33, categoryName: "Leafy Vegetables", variants: ["250g", "500g", "1 kg"], description: "Fresh sarson leaves, the star of classic winter dish sarson ka saag with makki roti.", rating: 4.2, reviewCount: 987, tags: ["leafy", "sarson", "mustard"] },
  { name: "Lettuce", price: 60, unit: "kg", quantity: "1 kg", categoryId: 33, categoryName: "Leafy Vegetables", variants: ["250g", "500g"], description: "Crisp fresh lettuce, perfect for salads, wraps, burgers, and sandwiches.", rating: 4.0, reviewCount: 543, tags: ["leafy", "lettuce", "salad"] },
  { name: "Amaranth Leaves", price: 15, unit: "bunch", quantity: "1 bunch", categoryId: 33, categoryName: "Leafy Vegetables", variants: [], description: "Fresh amaranth leaves (chaulai saag), nutritious leafy green popular in Indian cooking.", rating: 4.0, reviewCount: 432, tags: ["leafy", "amaranth", "chaulai"] },

  // ───── ROOT VEGETABLES (34) ─────
  { name: "Carrot", price: 35, unit: "kg", quantity: "1 kg", categoryId: 34, categoryName: "Root Vegetables", variants: ["250g", "500g", "1 kg"], description: "Farm-fresh carrots (gajar), rich in beta-carotene. Great for salads, halwa, and juices.", rating: 4.3, reviewCount: 2156, tags: ["root", "carrot", "gajar"] },
  { name: "Beetroot", price: 30, unit: "kg", quantity: "1 kg", categoryId: 34, categoryName: "Root Vegetables", variants: ["250g", "500g", "1 kg"], description: "Deep red beetroots, packed with nutrients. Perfect for salads, juices, and curries.", rating: 4.2, reviewCount: 1234, tags: ["root", "beetroot"] },
  { name: "Radish", price: 20, unit: "kg", quantity: "1 kg", categoryId: 34, categoryName: "Root Vegetables", variants: ["250g", "500g", "1 kg"], description: "Fresh white radish (mooli), crunchy and peppery. Great for salads and mooli parathas.", rating: 4.0, reviewCount: 876, tags: ["root", "radish", "mooli"] },
  { name: "Garlic", price: 100, unit: "kg", quantity: "500g", categoryId: 34, categoryName: "Root Vegetables", variants: ["100g", "250g", "500g"], description: "Fresh garlic (lehsun), the flavor foundation of Indian cooking. Aromatic and pungent.", rating: 4.5, reviewCount: 4321, tags: ["root", "garlic", "lehsun"] },
  { name: "Ginger", price: 100, unit: "kg", quantity: "250g", categoryId: 34, categoryName: "Root Vegetables", variants: ["100g", "250g", "500g"], description: "Fresh ginger (adrak), adds warmth and spice to curries, chai, and chutneys.", rating: 4.5, reviewCount: 5678, tags: ["root", "ginger", "adrak"] },
  { name: "Sweet Potato", price: 40, unit: "kg", quantity: "1 kg", categoryId: 34, categoryName: "Root Vegetables", variants: ["250g", "500g", "1 kg"], description: "Naturally sweet sweet potatoes (shakarkand), perfect for chaat and vrat (fasting) foods.", rating: 4.2, reviewCount: 1098, tags: ["root", "sweet potato", "shakarkand"] },
  { name: "Taro Root", price: 45, unit: "kg", quantity: "1 kg", categoryId: 34, categoryName: "Root Vegetables", variants: ["250g", "500g", "1 kg"], description: "Taro root (arbi / colocasia), a starchy root vegetable great for curries and fry.", rating: 4.0, reviewCount: 654, tags: ["root", "taro", "arbi"] },
  { name: "Yam", price: 45, unit: "kg", quantity: "1 kg", categoryId: 34, categoryName: "Root Vegetables", variants: ["250g", "500g", "1 kg"], description: "Fresh yam (suran / elephant yam), earthy and nutritious. Great for curries and chips.", rating: 3.9, reviewCount: 432, tags: ["root", "yam", "suran"] },
  { name: "Turnip", price: 25, unit: "kg", quantity: "1 kg", categoryId: 34, categoryName: "Root Vegetables", variants: ["250g", "500g", "1 kg"], description: "Fresh turnips (shalgam), mildly sweet root vegetable used in curries, pickles, and stews.", rating: 3.8, reviewCount: 321, tags: ["root", "turnip", "shalgam"] },

  // ───── EXOTIC VEGETABLES (35) ─────
  { name: "Broccoli", price: 70, unit: "kg", quantity: "500g", categoryId: 35, categoryName: "Exotic Vegetables", variants: ["250g", "500g", "1 kg"], description: "Nutritious broccoli florets, loaded with vitamins C and K. Great stir-fried, steamed, or in soups.", rating: 4.2, reviewCount: 1543, tags: ["exotic", "broccoli"] },
  { name: "Red Capsicum", price: 80, unit: "kg", quantity: "1 kg", categoryId: 35, categoryName: "Exotic Vegetables", variants: ["250g", "500g", "1 kg"], description: "Vibrant red capsicums, sweeter than green variety. Perfect for salads and stir-fries.", rating: 4.3, reviewCount: 1234, tags: ["exotic", "capsicum", "red pepper"] },
  { name: "Yellow Capsicum", price: 80, unit: "kg", quantity: "1 kg", categoryId: 35, categoryName: "Exotic Vegetables", variants: ["250g", "500g", "1 kg"], description: "Bright yellow capsicums, mild and sweet. Adds beautiful color and crunch to dishes.", rating: 4.2, reviewCount: 987, tags: ["exotic", "capsicum", "yellow pepper"] },
  { name: "Button Mushroom", price: 150, unit: "kg", quantity: "200g", categoryId: 35, categoryName: "Exotic Vegetables", variants: ["200g", "500g"], description: "Fresh button mushrooms, earthy and meaty. Perfect for curries, pasta, and soups.", rating: 4.3, reviewCount: 2341, tags: ["exotic", "mushroom"] },
  { name: "Baby Corn", price: 80, unit: "kg", quantity: "200g", categoryId: 35, categoryName: "Exotic Vegetables", variants: ["200g", "500g"], description: "Tender baby corn cobs, crisp and sweet. Perfect for stir-fries, salads, and Indo-Chinese dishes.", rating: 4.1, reviewCount: 876, tags: ["exotic", "baby corn"] },
  { name: "Zucchini", price: 60, unit: "kg", quantity: "1 kg", categoryId: 35, categoryName: "Exotic Vegetables", variants: ["250g", "500g", "1 kg"], description: "Fresh zucchini (courgette), mild squash great for pasta, soups, and stir-fries.", rating: 4.0, reviewCount: 654, tags: ["exotic", "zucchini", "courgette"] },
  { name: "Cherry Tomato", price: 100, unit: "kg", quantity: "250g", categoryId: 35, categoryName: "Exotic Vegetables", variants: ["250g", "500g"], description: "Sweet cherry tomatoes, perfect for salads, pasta, roasting, and snacking.", rating: 4.4, reviewCount: 1876, tags: ["exotic", "tomato", "cherry"] },
  { name: "Asparagus", price: 200, unit: "kg", quantity: "250g", categoryId: 35, categoryName: "Exotic Vegetables", variants: ["250g", "500g"], description: "Tender asparagus spears, great for salads, soups, and light stir-fries.", rating: 4.0, reviewCount: 432, tags: ["exotic", "asparagus"] },

  // ───── GOURDS & SQUASH (38) ─────
  { name: "Bottle Gourd", price: 25, unit: "kg", quantity: "1 kg", categoryId: 38, categoryName: "Gourds & Squash", variants: ["500g", "1 kg"], description: "Fresh bottle gourd (lauki / doodhi), light and nutritious. Perfect for curry and halwa.", rating: 4.0, reviewCount: 1234, tags: ["gourd", "lauki", "bottle gourd"] },
  { name: "Ridge Gourd", price: 30, unit: "kg", quantity: "1 kg", categoryId: 38, categoryName: "Gourds & Squash", variants: ["500g", "1 kg"], description: "Tender ridge gourd (turai), great for simple sabzi and dal preparations.", rating: 3.9, reviewCount: 765, tags: ["gourd", "turai", "ridge gourd"] },
  { name: "Bitter Gourd", price: 35, unit: "kg", quantity: "1 kg", categoryId: 38, categoryName: "Gourds & Squash", variants: ["250g", "500g", "1 kg"], description: "Fresh bitter gourd (karela), prized for its blood sugar benefits and unique bitter taste.", rating: 4.1, reviewCount: 1098, tags: ["gourd", "karela", "bitter gourd"] },
  { name: "Pumpkin", price: 20, unit: "kg", quantity: "1 kg", categoryId: 38, categoryName: "Gourds & Squash", variants: ["500g", "1 kg"], description: "Fresh orange pumpkin (kaddu), sweet and nutritious. Great for sabzi and pumpkin halwa.", rating: 4.0, reviewCount: 876, tags: ["gourd", "pumpkin", "kaddu"] },
  { name: "Ash Gourd", price: 20, unit: "kg", quantity: "1 kg", categoryId: 38, categoryName: "Gourds & Squash", variants: ["500g", "1 kg"], description: "Fresh ash gourd (petha / white gourd), used for famous Agra petha sweet and healthy juices.", rating: 3.8, reviewCount: 432, tags: ["gourd", "ash gourd", "petha"] },
  { name: "Pointed Gourd", price: 40, unit: "kg", quantity: "1 kg", categoryId: 38, categoryName: "Gourds & Squash", variants: ["250g", "500g", "1 kg"], description: "Fresh pointed gourd (parwal), a popular summer vegetable in Bengali and North Indian cuisine.", rating: 4.0, reviewCount: 654, tags: ["gourd", "parwal", "pointed gourd"] },
  { name: "Snake Gourd", price: 30, unit: "kg", quantity: "1 kg", categoryId: 38, categoryName: "Gourds & Squash", variants: ["500g", "1 kg"], description: "Long snake gourd (chichinda / padwal), tender and mild. Great for South Indian curries.", rating: 3.9, reviewCount: 321, tags: ["gourd", "snake gourd", "chichinda"] },
  { name: "Sponge Gourd", price: 25, unit: "kg", quantity: "1 kg", categoryId: 38, categoryName: "Gourds & Squash", variants: ["500g", "1 kg"], description: "Fresh sponge gourd (gilka / torai), light and easily digestible. Perfect for everyday cooking.", rating: 3.8, reviewCount: 432, tags: ["gourd", "sponge gourd", "gilka"] },

  // ───── BEANS & PODS (39) ─────
  { name: "French Beans", price: 50, unit: "kg", quantity: "500g", categoryId: 39, categoryName: "Beans & Pods", variants: ["250g", "500g", "1 kg"], description: "Tender green beans (French beans), crisp and flavorful. Perfect for stir-fries and salads.", rating: 4.2, reviewCount: 1234, tags: ["beans", "french beans", "green beans"] },
  { name: "Cluster Beans", price: 40, unit: "kg", quantity: "500g", categoryId: 39, categoryName: "Beans & Pods", variants: ["250g", "500g", "1 kg"], description: "Slender cluster beans (gavar), great for sabzi and dal preparations in Gujarati cuisine.", rating: 4.0, reviewCount: 765, tags: ["beans", "gavar", "cluster beans"] },
  { name: "Broad Beans", price: 45, unit: "kg", quantity: "500g", categoryId: 39, categoryName: "Beans & Pods", variants: ["250g", "500g", "1 kg"], description: "Fresh broad beans (papdi / sem), great for winter curries and Gujarati surti papdi nu shaak.", rating: 4.1, reviewCount: 876, tags: ["beans", "broad beans", "papdi"] },
  { name: "Runner Beans", price: 50, unit: "kg", quantity: "500g", categoryId: 39, categoryName: "Beans & Pods", variants: ["250g", "500g", "1 kg"], description: "Fresh flat runner beans, tender and meaty. Perfect for Indian sabzi.", rating: 3.9, reviewCount: 432, tags: ["beans", "runner beans"] },
  { name: "Hyacinth Beans", price: 45, unit: "kg", quantity: "500g", categoryId: 39, categoryName: "Beans & Pods", variants: ["250g", "500g", "1 kg"], description: "Fresh hyacinth beans (sem / valor papdi), popular in Gujarati and Maharashtrian cuisine.", rating: 4.0, reviewCount: 543, tags: ["beans", "sem", "hyacinth beans", "valor"] },

  // ───── FRUITS (18) ─────
  { name: "Apple", price: 150, unit: "kg", quantity: "1 kg (4-6 pcs)", categoryId: 18, categoryName: "Fruits", variants: ["500g", "1 kg", "2 kg"], description: "Crisp and sweet apples — a daily fruit for good health. Rich in fiber and vitamins.", rating: 4.4, reviewCount: 5678, tags: ["fruit", "apple"] },
  { name: "Banana", price: 45, unit: "kg", quantity: "1 kg (6-8 pcs)", categoryId: 18, categoryName: "Fruits", variants: ["500g", "1 kg", "2 kg"], description: "Sweet ripe bananas (kela), an energy-packed snack. Great for smoothies and breakfast.", rating: 4.5, reviewCount: 7654, tags: ["fruit", "banana", "kela"] },
  { name: "Pomegranate", price: 120, unit: "kg", quantity: "1 kg (2 pcs)", categoryId: 18, categoryName: "Fruits", variants: ["500g", "1 kg"], description: "Ruby-red pomegranate (anar), packed with antioxidants. A superfood fruit.", rating: 4.4, reviewCount: 3421, tags: ["fruit", "pomegranate", "anar"] },
  { name: "Guava", price: 65, unit: "kg", quantity: "1 kg", categoryId: 18, categoryName: "Fruits", variants: ["500g", "1 kg"], description: "Fresh guavas (amrood), tropical and fragrant. Rich in vitamin C. Great eaten with chaat masala.", rating: 4.3, reviewCount: 2341, tags: ["fruit", "guava", "amrood"] },
  { name: "Papaya", price: 35, unit: "kg", quantity: "1 kg", categoryId: 18, categoryName: "Fruits", variants: ["500g", "1 kg", "2 kg"], description: "Ripe papaya (papita), sweet and digestive. Great for breakfast, smoothies, and as raw in salads.", rating: 4.2, reviewCount: 1876, tags: ["fruit", "papaya", "papita"] },
  { name: "Chiku", price: 60, unit: "kg", quantity: "1 kg", categoryId: 18, categoryName: "Fruits", variants: ["500g", "1 kg"], description: "Sweet chiku (sapota / naseberry), brown-skinned fruit with honey-like caramel taste.", rating: 4.2, reviewCount: 1234, tags: ["fruit", "chiku", "sapota"] },
  { name: "Pear", price: 130, unit: "kg", quantity: "1 kg (4-5 pcs)", categoryId: 18, categoryName: "Fruits", variants: ["500g", "1 kg"], description: "Juicy pears (nashpati), crisp and refreshing. A versatile fruit for snacking and smoothies.", rating: 4.1, reviewCount: 987, tags: ["fruit", "pear", "nashpati"] },
  { name: "Custard Apple", price: 100, unit: "kg", quantity: "500g", categoryId: 18, categoryName: "Fruits", variants: ["500g", "1 kg"], description: "Creamy custard apple (sitaphal / sharifa), naturally sweet, fragrant, and delicious.", rating: 4.3, reviewCount: 1543, tags: ["fruit", "custard apple", "sitaphal", "sharifa"] },
  { name: "Fig", price: 200, unit: "kg", quantity: "250g", categoryId: 18, categoryName: "Fruits", variants: ["250g", "500g"], description: "Fresh figs (anjeer), soft and honey-sweet. A nutritious fruit great for snacking.", rating: 4.2, reviewCount: 876, tags: ["fruit", "fig", "anjeer"] },

  // ───── TROPICAL FRUITS (36) ─────
  { name: "Mango", price: 120, unit: "kg", quantity: "1 kg (3-4 pcs)", categoryId: 36, categoryName: "Tropical Fruits", variants: ["500g", "1 kg", "2 kg"], description: "The king of fruits! Sweet and fragrant Indian mangoes, perfect fresh, in juices, and desserts.", rating: 4.8, reviewCount: 9876, tags: ["tropical", "mango", "aam"] },
  { name: "Pineapple", price: 55, unit: "kg", quantity: "1 pc", categoryId: 36, categoryName: "Tropical Fruits", variants: [], description: "Tropical pineapple (ananas), tangy-sweet and fibrous. Perfect for juices, salads, and desserts.", rating: 4.3, reviewCount: 2341, tags: ["tropical", "pineapple", "ananas"] },
  { name: "Coconut", price: 35, unit: "pc", quantity: "1 pc", categoryId: 36, categoryName: "Tropical Fruits", variants: [], description: "Fresh whole coconut (nariyal), essential for South Indian cooking, sweets, and chutneys.", rating: 4.4, reviewCount: 4321, tags: ["tropical", "coconut", "nariyal"] },
  { name: "Lychee", price: 100, unit: "kg", quantity: "500g", categoryId: 36, categoryName: "Tropical Fruits", variants: ["250g", "500g", "1 kg"], description: "Juicy lychees (litchi), fragrant summer fruit with delicate sweet white flesh.", rating: 4.5, reviewCount: 3421, tags: ["tropical", "lychee", "litchi"] },
  { name: "Dragon Fruit", price: 150, unit: "kg", quantity: "1 pc", categoryId: 36, categoryName: "Tropical Fruits", variants: ["500g", "1 kg"], description: "Exotic dragon fruit with vibrant pink skin and spotted white flesh. A stunning superfood.", rating: 4.3, reviewCount: 2134, tags: ["tropical", "dragon fruit"] },
  { name: "Jackfruit", price: 60, unit: "kg", quantity: "1 kg", categoryId: 36, categoryName: "Tropical Fruits", variants: ["500g", "1 kg", "2 kg"], description: "Fresh jackfruit (kathal), tropical giant with sweet pods when ripe, great for biryani when raw.", rating: 4.2, reviewCount: 1234, tags: ["tropical", "jackfruit", "kathal"] },
  { name: "Star Fruit", price: 80, unit: "kg", quantity: "500g", categoryId: 36, categoryName: "Tropical Fruits", variants: ["250g", "500g"], description: "Star-shaped carambola (kamrakh), tangy and crisp. Beautiful star slices make stunning garnish.", rating: 4.0, reviewCount: 432, tags: ["tropical", "star fruit", "carambola", "kamrakh"] },
  { name: "Rambutan", price: 200, unit: "kg", quantity: "500g", categoryId: 36, categoryName: "Tropical Fruits", variants: ["250g", "500g"], description: "Exotic hairy red rambutan, tropical fruit with sweet translucent flesh similar to lychee.", rating: 4.1, reviewCount: 654, tags: ["tropical", "rambutan"] },
  { name: "Longan", price: 150, unit: "kg", quantity: "500g", categoryId: 36, categoryName: "Tropical Fruits", variants: ["250g", "500g"], description: "Sweet longan (dragon eyes), small round tropical fruit with thin shell and sweet white flesh.", rating: 4.0, reviewCount: 432, tags: ["tropical", "longan"] },

  // ───── CITRUS FRUITS (37) ─────
  { name: "Orange", price: 65, unit: "kg", quantity: "1 kg (4-5 pcs)", categoryId: 37, categoryName: "Citrus Fruits", variants: ["500g", "1 kg", "2 kg"], description: "Juicy oranges (santra / narangi), vitamin C powerhouse. Great for fresh juice.", rating: 4.4, reviewCount: 4321, tags: ["citrus", "orange", "santra"] },
  { name: "Lemon", price: 60, unit: "kg", quantity: "1 kg (8-10 pcs)", categoryId: 37, categoryName: "Citrus Fruits", variants: ["100g", "250g", "500g", "1 kg"], description: "Fresh lemons (nimbu), essential for Indian cooking, nimbu pani, and chutneys.", rating: 4.5, reviewCount: 6789, tags: ["citrus", "lemon", "nimbu"] },
  { name: "Sweet Lime", price: 55, unit: "kg", quantity: "1 kg", categoryId: 37, categoryName: "Citrus Fruits", variants: ["500g", "1 kg", "2 kg"], description: "Fresh sweet lime (mosambi), naturally sweet citrus. Perfect for fresh juice.", rating: 4.4, reviewCount: 3456, tags: ["citrus", "sweet lime", "mosambi"] },
  { name: "Grapefruit", price: 80, unit: "kg", quantity: "1 kg (2-3 pcs)", categoryId: 37, categoryName: "Citrus Fruits", variants: ["500g", "1 kg"], description: "Tart and refreshing grapefruit, great for weight management and a healthy breakfast.", rating: 4.0, reviewCount: 543, tags: ["citrus", "grapefruit"] },
  { name: "Pomelo", price: 50, unit: "kg", quantity: "1 pc", categoryId: 37, categoryName: "Citrus Fruits", variants: [], description: "Mild pomelo (chakotra), the largest citrus fruit. Great for salads and fresh juicing.", rating: 4.0, reviewCount: 432, tags: ["citrus", "pomelo", "chakotra"] },
  { name: "Kinnow", price: 80, unit: "kg", quantity: "1 kg", categoryId: 37, categoryName: "Citrus Fruits", variants: ["500g", "1 kg", "2 kg"], description: "Punjab's famous kinnow mandarin, intensely fragrant and sweet. A winter season special.", rating: 4.4, reviewCount: 2134, tags: ["citrus", "kinnow", "mandarin"] },
  { name: "Lime", price: 60, unit: "kg", quantity: "500g", categoryId: 37, categoryName: "Citrus Fruits", variants: ["100g", "250g", "500g"], description: "Fresh limes (kagzi nimbu), small and very juicy. Perfect for cocktails, chutneys, and cooking.", rating: 4.3, reviewCount: 1234, tags: ["citrus", "lime", "kagzi nimbu"] },

  // ───── BERRIES & GRAPES (40) ─────
  { name: "Strawberry", price: 150, unit: "kg", quantity: "500g", categoryId: 40, categoryName: "Berries & Grapes", variants: ["250g", "500g", "1 kg"], description: "Sweet-tart strawberries, bursting with flavor. Perfect for desserts, jams, and smoothies.", rating: 4.5, reviewCount: 4321, tags: ["berry", "strawberry"] },
  { name: "Green Grapes", price: 80, unit: "kg", quantity: "500g", categoryId: 40, categoryName: "Berries & Grapes", variants: ["500g", "1 kg", "2 kg"], description: "Crisp seedless green grapes (angoor), refreshing and sweet. Perfect for snacking.", rating: 4.4, reviewCount: 3421, tags: ["grape", "green grapes", "angoor"] },
  { name: "Black Grapes", price: 80, unit: "kg", quantity: "500g", categoryId: 40, categoryName: "Berries & Grapes", variants: ["500g", "1 kg", "2 kg"], description: "Deep purple-black grapes, rich in antioxidants and naturally sweet. A healthy snack.", rating: 4.3, reviewCount: 2876, tags: ["grape", "black grapes", "angoor"] },
  { name: "Kiwi", price: 200, unit: "kg", quantity: "4 pcs", categoryId: 40, categoryName: "Berries & Grapes", variants: ["4 pcs", "6 pcs"], description: "Tangy-sweet kiwi fruit, packed with vitamin C and dietary fiber. Great for fruit salads.", rating: 4.3, reviewCount: 2341, tags: ["berry", "kiwi"] },
  { name: "Blueberry", price: 600, unit: "kg", quantity: "125g", categoryId: 40, categoryName: "Berries & Grapes", variants: ["125g", "250g"], description: "Fresh blueberries, a superfood berry loaded with antioxidants. Great for yogurt and smoothies.", rating: 4.4, reviewCount: 1876, tags: ["berry", "blueberry"] },
  { name: "Gooseberry", price: 35, unit: "kg", quantity: "500g", categoryId: 40, categoryName: "Berries & Grapes", variants: ["250g", "500g", "1 kg"], description: "Fresh Indian gooseberry (amla), vitamin C superfood. Used in pickles, murabba, and health drinks.", rating: 4.2, reviewCount: 1543, tags: ["berry", "amla", "gooseberry"] },
  { name: "Mulberry", price: 150, unit: "kg", quantity: "250g", categoryId: 40, categoryName: "Berries & Grapes", variants: ["250g", "500g"], description: "Sweet-tart mulberries (shahtoot), seasonal summer berry with deep purple staining juice.", rating: 4.1, reviewCount: 765, tags: ["berry", "mulberry", "shahtoot"] },
  { name: "Raspberry", price: 300, unit: "kg", quantity: "125g", categoryId: 40, categoryName: "Berries & Grapes", variants: ["125g", "250g"], description: "Delicate raspberries, tangy-sweet and fragrant. Great for desserts, jams, and smoothies.", rating: 4.2, reviewCount: 876, tags: ["berry", "raspberry"] },

  // ───── MELONS (41) ─────
  { name: "Watermelon", price: 25, unit: "kg", quantity: "1 kg", categoryId: 41, categoryName: "Melons", variants: ["1 kg", "2 kg", "4 kg"], description: "Sweet, juicy watermelon (tarbuz), the perfect summer refresher. 92% water and rich in lycopene.", rating: 4.6, reviewCount: 5432, tags: ["melon", "watermelon", "tarbuz"] },
  { name: "Muskmelon", price: 35, unit: "kg", quantity: "1 pc", categoryId: 41, categoryName: "Melons", variants: [], description: "Fragrant muskmelon (kharbooja), naturally sweet summer fruit. Great for fresh juice.", rating: 4.4, reviewCount: 3421, tags: ["melon", "muskmelon", "kharbooja"] },
  { name: "Honeydew Melon", price: 45, unit: "kg", quantity: "1 pc", categoryId: 41, categoryName: "Melons", variants: [], description: "Sweet honeydew melon with smooth green skin and pale flesh. A refreshing summer treat.", rating: 4.2, reviewCount: 1234, tags: ["melon", "honeydew"] },
  { name: "Cantaloupe", price: 40, unit: "kg", quantity: "1 pc", categoryId: 41, categoryName: "Melons", variants: [], description: "Sweet orange-fleshed cantaloupe melon, loaded with vitamins A and C. Summer essential.", rating: 4.3, reviewCount: 987, tags: ["melon", "cantaloupe"] },

  // ───── STONE FRUITS (42) ─────
  { name: "Plum", price: 120, unit: "kg", quantity: "500g", categoryId: 42, categoryName: "Stone Fruits", variants: ["250g", "500g", "1 kg"], description: "Sweet-tart plums (aloo bukhara), juicy stone fruit with smooth skin and sweet flesh.", rating: 4.2, reviewCount: 1543, tags: ["stone fruit", "plum", "aloo bukhara"] },
  { name: "Peach", price: 140, unit: "kg", quantity: "500g", categoryId: 42, categoryName: "Stone Fruits", variants: ["250g", "500g", "1 kg"], description: "Fragrant peaches (aadoo), fuzzy-skinned stone fruit with sweet, intensely juicy flesh.", rating: 4.3, reviewCount: 1234, tags: ["stone fruit", "peach", "aadoo"] },
  { name: "Cherry", price: 300, unit: "kg", quantity: "250g", categoryId: 42, categoryName: "Stone Fruits", variants: ["250g", "500g"], description: "Premium dark red cherries, naturally sweet and plump. A special summer treat.", rating: 4.4, reviewCount: 2134, tags: ["stone fruit", "cherry"] },
  { name: "Apricot", price: 200, unit: "kg", quantity: "500g", categoryId: 42, categoryName: "Stone Fruits", variants: ["250g", "500g", "1 kg"], description: "Fresh apricots (khumani / jardalu), golden-orange stone fruit with sweet-tangy taste.", rating: 4.1, reviewCount: 876, tags: ["stone fruit", "apricot", "khumani"] },
  { name: "Jamun", price: 80, unit: "kg", quantity: "500g", categoryId: 42, categoryName: "Stone Fruits", variants: ["250g", "500g", "1 kg"], description: "Indian blackberry (jamun), with deep purple astringent-sweet taste. Classic monsoon fruit.", rating: 4.3, reviewCount: 1876, tags: ["stone fruit", "jamun", "indian blackberry"] },
  { name: "Indian Jujube", price: 60, unit: "kg", quantity: "1 kg", categoryId: 42, categoryName: "Stone Fruits", variants: ["250g", "500g", "1 kg"], description: "Fresh Indian jujube (ber), a winter crunchy fruit popular across India as street food.", rating: 4.1, reviewCount: 987, tags: ["stone fruit", "ber", "jujube"] },
  { name: "Loquat", price: 100, unit: "kg", quantity: "500g", categoryId: 42, categoryName: "Stone Fruits", variants: ["250g", "500g"], description: "Sweet loquats (lukath), small oval stone fruits with delicate citrus-honey flavor.", rating: 4.0, reviewCount: 432, tags: ["stone fruit", "loquat"] },
];
